// GENERATED ONCE from the former FUNCTION_ROWS, now the source of truth for
// each node's Excel equivalence. Applied onto catalog leaves by buildCatalog
// (like NODE_PACK_TAGS). Pack nodes may instead declare `excel` inline on their
// entry. The dev catalog validator flags any Excel-mapped node missing metadata,
// so this can't silently go stale (the bug that left LAMBDA marked "to-do").
import type { ExcelEquiv } from "./AddNodeMenu";

/** catalog node type -> the Excel function(s) it stands in for. */
export const NODE_EXCEL: Record<string, ExcelEquiv[]> = {
  "accrint": [{ excel: "ACCRINT", syntax: "=ACCRINT(issue,first,settle,rate,par,freq)", parity: false, note: "Accrued interest; not yet supported" }],
  "accrintm": [{ excel: "ACCRINTM", syntax: "=ACCRINTM(issue,settle,rate,par)", parity: false, note: "Accrued interest at maturity; not yet supported" }],
  "arith-mod": [{ excel: "MOD", syntax: "=MOD(a, b)", parity: true }],
  "arith-pow": [{ excel: "POWER", syntax: "=POWER(x, n)", parity: true }],
  "arith-quotient": [{ excel: "QUOTIENT", syntax: "=QUOTIENT(a, b)", parity: true }],
  "base-convert": [
    { excel: "BASE", syntax: "=BASE(n, radix)", parity: false, note: "Excel outputs text; Solenoid outputs a number (A–F digits not representable)" },
    { excel: "DECIMAL", syntax: "=DECIMAL(text, radix)", parity: false, note: "Excel takes a text string; Solenoid takes the decimal digit-string as a number" },
    { excel: "BIN2DEC", syntax: "=BIN2DEC(number)", parity: false, note: "Use Base Convert node: from=2, to=10" },
    { excel: "BIN2HEX", syntax: "=BIN2HEX(number)", parity: false, note: "Use Base Convert node: from=2, to=16 (hex output returns null; no A–F)" },
    { excel: "BIN2OCT", syntax: "=BIN2OCT(number)", parity: false, note: "Use Base Convert node: from=2, to=8" },
    { excel: "DEC2BIN", syntax: "=DEC2BIN(number)", parity: false, note: "Use Base Convert node: from=10, to=2" },
    { excel: "DEC2HEX", syntax: "=DEC2HEX(number)", parity: false, note: "Use Base Convert node: from=10, to=16 (returns null when digits > 9)" },
    { excel: "DEC2OCT", syntax: "=DEC2OCT(number)", parity: false, note: "Use Base Convert node: from=10, to=8" },
    { excel: "HEX2BIN", syntax: "=HEX2BIN(number)", parity: false, note: "Use Base Convert node: from=16, to=2 (hex input digits A–F not enterable)" },
    { excel: "HEX2DEC", syntax: "=HEX2DEC(number)", parity: false, note: "Use Base Convert node: from=16, to=10 (hex input digits A–F not enterable)" },
    { excel: "HEX2OCT", syntax: "=HEX2OCT(number)", parity: false, note: "Use Base Convert node: from=16, to=8 (hex input digits A–F not enterable)" },
    { excel: "OCT2BIN", syntax: "=OCT2BIN(number)", parity: false, note: "Use Base Convert node: from=8, to=2" },
    { excel: "OCT2DEC", syntax: "=OCT2DEC(number)", parity: false, note: "Use Base Convert node: from=8, to=10" },
    { excel: "OCT2HEX", syntax: "=OCT2HEX(number)", parity: false, note: "Use Base Convert node: from=8, to=16 (hex output returns null; no A–F)" },
  ],
  "bessel-besseli": [{ excel: "BESSELI", syntax: "=BESSELI(x, n)", parity: false, note: "x must be ≥ 0; n must be a non-negative integer" }],
  "bessel-besselj": [{ excel: "BESSELJ", syntax: "=BESSELJ(x, n)", parity: false, note: "n must be a non-negative integer" }],
  "bessel-besselk": [{ excel: "BESSELK", syntax: "=BESSELK(x, n)", parity: false, note: "x must be > 0; n must be a non-negative integer" }],
  "bessel-bessely": [{ excel: "BESSELY", syntax: "=BESSELY(x, n)", parity: false, note: "x must be > 0; n must be a non-negative integer" }],
  "betadist": [{ excel: "BETA.DIST", syntax: "=BETA.DIST(x, α, β, cum)", parity: true }],
  "betainv": [{ excel: "BETA.INV", syntax: "=BETA.INV(p, α, β)", parity: true }],
  "binomdist": [{ excel: "BINOM.DIST", syntax: "=BINOM.DIST(k, n, p, cum)", parity: true }],
  "binomdistrng": [{ excel: "BINOM.DIST.RANGE", syntax: "=BINOM.DIST.RANGE(n, p, lo, hi)" }],
  "binominv": [{ excel: "BINOM.INV", syntax: "=BINOM.INV(n, p, α)" }],
  "bitwise-bitand": [{ excel: "BITAND", syntax: "=BITAND(a, b)", parity: true }],
  "bitwise-bitlshift": [{ excel: "BITLSHIFT", syntax: "=BITLSHIFT(a, n)", parity: true }],
  "bitwise-bitor": [{ excel: "BITOR", syntax: "=BITOR(a, b)", parity: true }],
  "bitwise-bitrshift": [{ excel: "BITRSHIFT", syntax: "=BITRSHIFT(a, n)", parity: true }],
  "bitwise-bitxor": [{ excel: "BITXOR", syntax: "=BITXOR(a, b)", parity: true }],
  "bondprice-price": [{ excel: "PRICE", syntax: "=PRICE(settle,maturity,rate,yld,redemption,freq)", parity: false, note: "30/360 basis only; other basis values not yet supported" }],
  "bondprice-yield": [{ excel: "YIELD", syntax: "=YIELD(settle,maturity,rate,pr,redemption,freq)", parity: false, note: "30/360 basis only" }],
  "by-axis": [
    { excel: "BYROW", syntax: "=BYROW(array, LAMBDA(row, ...))", parity: false, note: "BYROW/BYCOL node reduces each row/column with its own formula of (v), or a wired LAMBDA value" },
    { excel: "BYCOL", syntax: "=BYCOL(array, LAMBDA(col, ...))", parity: false, note: "BYROW/BYCOL node reduces each row/column with its own formula of (v), or a wired LAMBDA value" },
  ],
  "char-code-char": [
    { excel: "CHAR", syntax: "=CHAR(code)", parity: false, note: "Full Unicode (=UNICHAR) — code point 0–1114111" },
    { excel: "UNICHAR", syntax: "=UNICHAR(code)", parity: true, note: "Same as CHAR in Solenoid — full Unicode range" },
  ],
  "char-code-code": [
    { excel: "CODE", syntax: "=CODE(text)", parity: false, note: "Returns Unicode code point (=UNICODE) — full Unicode range" },
    { excel: "UNICODE", syntax: "=UNICODE(text)", parity: true, note: "Same as CODE in Solenoid — full Unicode range" },
  ],
  "chisq-test": [{ excel: "CHISQ.TEST", syntax: "=CHISQ.TEST(obs, exp)" }],
  "chisqdist": [
    { excel: "CHISQ.DIST", syntax: "=CHISQ.DIST(x, df, cum)", parity: true },
    { excel: "CHISQ.DIST.RT", syntax: "=CHISQ.DIST.RT(x, df)", parity: true },
  ],
  "chisqinv": [
    { excel: "CHISQ.INV", syntax: "=CHISQ.INV(p, df)", parity: true },
    { excel: "CHISQ.INV.RT", syntax: "=CHISQ.INV.RT(p, df)", parity: true },
  ],
  "choose": [{ excel: "CHOOSE", syntax: "=CHOOSE(idx, v1, v2, ...)", parity: true }],
  "comb-combin": [{ excel: "COMBIN", syntax: "=COMBIN(n, k)", parity: true }],
  "comb-combina": [{ excel: "COMBINA", syntax: "=COMBINA(n, k)", parity: true }],
  "comb-fact": [{ excel: "FACT", syntax: "=FACT(n)", parity: true }],
  "comb-factdouble": [{ excel: "FACTDOUBLE", syntax: "=FACTDOUBLE(n)", parity: true }],
  "comb-permut": [{ excel: "PERMUT", syntax: "=PERMUT(n, k)", parity: true }],
  "comb-permutationa": [{ excel: "PERMUTATIONA", syntax: "=PERMUTATIONA(n, k)" }],
  "confidence-norm": [{ excel: "CONFIDENCE.NORM", syntax: "=CONFIDENCE.NORM(α, σ, n)", parity: true }],
  "confidence-t": [{ excel: "CONFIDENCE.T", syntax: "=CONFIDENCE.T(α, σ, n)", parity: true }],
  "constant": [
    { excel: "PI", syntax: "=PI()", parity: true },
    { excel: "FALSE", syntax: "=FALSE()", parity: true },
    { excel: "TRUE", syntax: "=TRUE()", parity: true },
  ],
  "convert": [
    { excel: "CONVERT", syntax: "=CONVERT(x, from, to)", parity: true },
    { excel: "DEGREES", syntax: "=DEGREES(angle)", parity: true },
    { excel: "RADIANS", syntax: "=RADIANS(angle)", parity: true },
  ],
  "correl-correl": [
    { excel: "CORREL", syntax: "=CORREL(x, y)", parity: true },
    { excel: "PEARSON", syntax: "=PEARSON(x, y)", parity: true, note: "PEARSON = CORREL" },
  ],
  "coupon-coupdaybs": [{ excel: "COUPDAYBS", syntax: "=COUPDAYBS(settle,maturity,freq)", parity: false, note: "Days from coupon start to settle; not yet supported" }],
  "coupon-coupdays": [{ excel: "COUPDAYS", syntax: "=COUPDAYS(settle,maturity,freq)", parity: false, note: "Days in coupon period; not yet supported" }],
  "coupon-coupdaysnc": [{ excel: "COUPDAYSNC", syntax: "=COUPDAYSNC(settle,maturity,freq)", parity: false, note: "Days from settle to next coupon; not yet supported" }],
  "coupon-coupncd": [{ excel: "COUPNCD", syntax: "=COUPNCD(settle,maturity,freq)", parity: false, note: "Next coupon date; not yet supported" }],
  "coupon-coupnum": [{ excel: "COUPNUM", syntax: "=COUPNUM(settle,maturity,freq)", parity: false, note: "Number of coupon periods; not yet supported" }],
  "coupon-couppcd": [{ excel: "COUPPCD", syntax: "=COUPPCD(settle,maturity,freq)", parity: false, note: "Previous coupon date; not yet supported" }],
  "cov-pop": [{ excel: "COVARIANCE.P", syntax: "=COVARIANCE.P(x, y)", parity: true }],
  "cov-samp": [{ excel: "COVARIANCE.S", syntax: "=COVARIANCE.S(x, y)", parity: true }],
  "cumpmt-cumipmt": [{ excel: "CUMIPMT", syntax: "=CUMIPMT(rate, nper, pv, st, end, type)", parity: true }],
  "cumpmt-cumprinc": [{ excel: "CUMPRINC", syntax: "=CUMPRINC(rate, nper, pv, st, end, type)", parity: true }],
  "cx-binary-div": [{ excel: "IMDIV", syntax: "=IMDIV(z1, z2)", parity: false }],
  "cx-binary-product": [{ excel: "IMPRODUCT", syntax: "=IMPRODUCT(z1, z2)", parity: false }],
  "cx-binary-sub": [{ excel: "IMSUB", syntax: "=IMSUB(z1, z2)", parity: false }],
  "cx-binary-sum": [{ excel: "IMSUM", syntax: "=IMSUM(z1, z2)", parity: false }],
  "cx-from": [{ excel: "COMPLEX", syntax: "=COMPLEX(real, imag)", parity: false, note: "Solenoid uses a typed complex socket (sky-blue); Excel encodes as text strings like \"3+4i\"" }],
  "cx-power": [{ excel: "IMPOWER", syntax: "=IMPOWER(z, n)", parity: false, note: "n is a real exponent; complex exponent not supported" }],
  "cx-unary-conj": [{ excel: "IMCONJUGATE", syntax: "=IMCONJUGATE(z)", parity: false }],
  "cx-unary-cos": [{ excel: "IMCOS", syntax: "=IMCOS(z)", parity: false }],
  "cx-unary-cosh": [{ excel: "IMCOSH", syntax: "=IMCOSH(z)", parity: false }],
  "cx-unary-cot": [{ excel: "IMCOT", syntax: "=IMCOT(z)", parity: false }],
  "cx-unary-csc": [{ excel: "IMCSC", syntax: "=IMCSC(z)", parity: false }],
  "cx-unary-csch": [{ excel: "IMCSCH", syntax: "=IMCSCH(z)", parity: false }],
  "cx-unary-exp": [{ excel: "IMEXP", syntax: "=IMEXP(z)", parity: false }],
  "cx-unary-ln": [{ excel: "IMLN", syntax: "=IMLN(z)", parity: false }],
  "cx-unary-log10": [{ excel: "IMLOG10", syntax: "=IMLOG10(z)", parity: false }],
  "cx-unary-log2": [{ excel: "IMLOG2", syntax: "=IMLOG2(z)", parity: false }],
  "cx-unary-sec": [{ excel: "IMSEC", syntax: "=IMSEC(z)", parity: false }],
  "cx-unary-sech": [{ excel: "IMSECH", syntax: "=IMSECH(z)", parity: false }],
  "cx-unary-sin": [{ excel: "IMSIN", syntax: "=IMSIN(z)", parity: false }],
  "cx-unary-sinh": [{ excel: "IMSINH", syntax: "=IMSINH(z)", parity: false }],
  "cx-unary-sqrt": [{ excel: "IMSQRT", syntax: "=IMSQRT(z)", parity: false }],
  "cx-unary-tan": [{ excel: "IMTAN", syntax: "=IMTAN(z)", parity: false }],
  "cx-unpack": [
    { excel: "IMABS", syntax: "=IMABS(z)", parity: false, note: "Use IM Unpack node — exposes Real, Imag, |z|, arg(z) simultaneously" },
    { excel: "IMAGINARY", syntax: "=IMAGINARY(z)", parity: false, note: "Use IM Unpack node" },
    { excel: "IMREAL", syntax: "=IMREAL(z)", parity: false, note: "Use IM Unpack node" },
    { excel: "IMARGUMENT", syntax: "=IMARGUMENT(z)", parity: false, note: "Use IM Unpack node" },
  ],
  "date-add-edate": [{ excel: "EDATE", syntax: "=EDATE(start, months)", parity: false }],
  "date-add-eomonth": [{ excel: "EOMONTH", syntax: "=EOMONTH(start, months)", parity: false }],
  "date-construct": [{ excel: "DATE", syntax: "=DATE(year, month, day)", parity: false }],
  "date-datedif": [{ excel: "DATEDIF", syntax: "=DATEDIF(start, end, unit)", parity: false, note: "MD borrows from the month before the end month; where Excel's documented-unreliable MD goes negative (e.g. Jan 31 → Mar 1) results may differ" }],
  "date-diff-days": [{ excel: "DAYS", syntax: "=DAYS(end_date, start_date)", parity: false }],
  "date-diff-days360": [{ excel: "DAYS360", syntax: "=DAYS360(start, end)", parity: false }],
  "date-diff-yearfrac": [{ excel: "YEARFRAC", syntax: "=YEARFRAC(start, end)", parity: false, note: "basis 1 (actual/actual) is approximated as ÷365.25" }],
  "date-networkdays": [
    { excel: "NETWORKDAYS", syntax: "=NETWORKDAYS(start, end)", parity: false },
    { excel: "NETWORKDAYS.INTL", syntax: "=NETWORKDAYS.INTL(start, end, wknd)", parity: false, note: "Use NETWORKDAYS with weekend_code input" },
  ],
  "date-now": [{ excel: "NOW", syntax: "=NOW()", parity: false }],
  "date-part-day": [{ excel: "DAY", syntax: "=DAY(date)", parity: false }],
  "date-part-hour": [{ excel: "HOUR", syntax: "=HOUR(time)", parity: false }],
  "date-part-minute": [{ excel: "MINUTE", syntax: "=MINUTE(time)", parity: false }],
  "date-part-month": [{ excel: "MONTH", syntax: "=MONTH(date)", parity: false }],
  "date-part-second": [{ excel: "SECOND", syntax: "=SECOND(time)", parity: false }],
  "date-part-year": [{ excel: "YEAR", syntax: "=YEAR(date)", parity: false }],
  "date-time": [{ excel: "TIME", syntax: "=TIME(hour, minute, second)", parity: false }],
  "date-today": [{ excel: "TODAY", syntax: "=TODAY()", parity: false }],
  "date-value": [{ excel: "DATEVALUE", syntax: "=DATEVALUE(date_text)", parity: false, note: "Accepts ISO 8601 format; browser-parsed" }],
  "date-week-isoweeknum": [{ excel: "ISOWEEKNUM", syntax: "=ISOWEEKNUM(date)", parity: false }],
  "date-week-weekday": [{ excel: "WEEKDAY", syntax: "=WEEKDAY(date)", parity: false }],
  "date-week-weeknum": [{ excel: "WEEKNUM", syntax: "=WEEKNUM(date)", parity: false }],
  "date-workday": [
    { excel: "WORKDAY", syntax: "=WORKDAY(start, days)", parity: false },
    { excel: "WORKDAY.INTL", syntax: "=WORKDAY.INTL(start, days, wknd)", parity: false, note: "Use WORKDAY with weekend_code input" },
  ],
  "depr-db": [{ excel: "DB", syntax: "=DB(cost, salv, life, per)", parity: true }],
  "depr-ddb": [{ excel: "DDB", syntax: "=DDB(cost, salv, life, per)", parity: true }],
  "depr-sln": [{ excel: "SLN", syntax: "=SLN(cost, salv, life)", parity: true }],
  "depr-syd": [{ excel: "SYD", syntax: "=SYD(cost, salv, life, per)", parity: true }],
  "dollar-dollarde": [{ excel: "DOLLARDE", syntax: "=DOLLARDE(frac_dollar, fraction)" }],
  "dollar-dollarfr": [{ excel: "DOLLARFR", syntax: "=DOLLARFR(decimal_dollar, fraction)" }],
  "duration-duration": [{ excel: "DURATION", syntax: "=DURATION(settle,maturity,coupon,yld,freq)", parity: false, note: "Macaulay duration; not yet supported" }],
  "duration-mduration": [{ excel: "MDURATION", syntax: "=MDURATION(settle,maturity,coupon,yld,freq)", parity: false, note: "Modified Macaulay duration; not yet supported" }],
  "expodist": [{ excel: "EXPON.DIST", syntax: "=EXPON.DIST(x, λ, cum)" }],
  "f-test": [{ excel: "F.TEST", syntax: "=F.TEST(a, b)" }],
  "fdist": [
    { excel: "F.DIST", syntax: "=F.DIST(x, d1, d2, cum)", parity: true },
    { excel: "F.DIST.RT", syntax: "=F.DIST.RT(x, d1, d2)", parity: true },
  ],
  "finv": [
    { excel: "F.INV", syntax: "=F.INV(p, d1, d2)", parity: true },
    { excel: "F.INV.RT", syntax: "=F.INV.RT(p, d1, d2)", parity: true },
  ],
  "fisher-fisher": [{ excel: "FISHER", syntax: "=FISHER(x)", parity: true }],
  "fisher-fisherinv": [{ excel: "FISHERINV", syntax: "=FISHERINV(y)", parity: true }],
  "forecast": [{ excel: "FORECAST.LINEAR", syntax: "=FORECAST.LINEAR(x, ys, xs)", parity: true }],
  "frequency": [{ excel: "FREQUENCY", syntax: "=FREQUENCY(data, bins)", parity: true }],
  "fvschedule": [{ excel: "FVSCHEDULE", syntax: "=FVSCHEDULE(pv, schedule)" }],
  "gammadist": [{ excel: "GAMMA.DIST", syntax: "=GAMMA.DIST(x, α, β, cum)", parity: true }],
  "gammainv": [{ excel: "GAMMA.INV", syntax: "=GAMMA.INV(p, α, β)", parity: true }],
  "gcd-lcm": [
    { excel: "GCD", syntax: "=GCD(a, b)", parity: true },
    { excel: "LCM", syntax: "=LCM(a, b)", parity: true },
  ],
  "hstack-table": [{ excel: "HSTACK", syntax: "=HSTACK(array1, array2, ...)", parity: true, note: "N-ary; ragged inputs pad with #N/A like Excel. A bare list counts as ONE ROW" }],
  "hypgeomdist": [{ excel: "HYPGEOM.DIST", syntax: "=HYPGEOM.DIST(s, ns, M, N, cum)" }],
  "iferror": [
    { excel: "IFERROR", syntax: "=IFERROR(v, fallback)", parity: true },
    { excel: "IFNA", syntax: "=IFNA(v, fallback)", parity: true },
  ],
  "ifs": [{ excel: "IFS", syntax: "=IFS(c1, v1, c2, v2, ...)", parity: false, note: "Fixed 3 conditions; Excel is variadic" }],
  "ipmt-ipmt": [{ excel: "IPMT", syntax: "=IPMT(rate, per, nper, pv)", parity: true }],
  "ipmt-ppmt": [{ excel: "PPMT", syntax: "=PPMT(rate, per, nper, pv)", parity: true }],
  "fin-effective-rate": [
    { excel: "EFFECT", syntax: "=EFFECT(rate, npery)", parity: true, note: "One Equation node: wire nom + npery, read eff" },
    { excel: "NOMINAL", syntax: "=NOMINAL(eff_rate, npery)", parity: true, note: "Same node the other way: wire eff + npery, read nom" },
  ],
  "fin-compound-growth": [
    { excel: "PDURATION", syntax: "=PDURATION(rate, pv, fv)", parity: true, note: "The Compound Growth equation solving for nper" },
    { excel: "RRI", syntax: "=RRI(nper, pv, fv)", parity: true, note: "The Compound Growth equation solving for rate" },
  ],
  "irr": [{ excel: "IRR", syntax: "=IRR(cashflows)", parity: true }],
  "is-test": [
    { excel: "ISBLANK", syntax: "=ISBLANK(v)", parity: true },
    { excel: "ISERR", syntax: "=ISERR(v)", parity: false, note: "ISERR excludes #N/A; Solenoid's ISERROR catches all non-finite values" },
    { excel: "ISERROR", syntax: "=ISERROR(v)", parity: true },
    { excel: "ISLOGICAL", syntax: "=ISLOGICAL(v)", parity: true, note: "TRUE only for a real boolean (TRUE/FALSE) — not 0/1 or \"TRUE\"; matches Excel's type check. Shown as ISBOOLEAN." },
    { excel: "ISNA", syntax: "=ISNA(v)", parity: false, note: "Returns 1 if value is N/A (NaN); use ISNA instead of ISERROR when testing only #N/A" },
    { excel: "ISNONTEXT", syntax: "=ISNONTEXT(v)", parity: false, note: "Returns 1 if value is not a string" },
    { excel: "ISNUMBER", syntax: "=ISNUMBER(v)", parity: true },
    { excel: "ISTEXT", syntax: "=ISTEXT(v)", parity: false, note: "Returns 1 if value is a string; wire from a Text input node" },
  ],
  "ispmt": [{ excel: "ISPMT", syntax: "=ISPMT(rate, per, nper, pv)" }],
  "linest": [
    { excel: "INTERCEPT", syntax: "=INTERCEPT(ys, xs)", parity: false, note: "Superseded by LINEST — use the Intercept output socket" },
    { excel: "LINEST", syntax: "=LINEST(ys, xs)", parity: false, note: "Returns [slope, intercept, r²] as a list; Excel returns a full 2×5 coefficient array" },
    { excel: "RSQ", syntax: "=RSQ(ys, xs)", parity: false, note: "Superseded by LINEST — use the R² output socket" },
    { excel: "SLOPE", syntax: "=SLOPE(ys, xs)", parity: false, note: "Superseded by LINEST — use the Slope output socket" },
  ],
  "lambda-make": [{ excel: "LAMBDA", syntax: "=LAMBDA(param, ..., calculation)", parity: false, note: "LAMBDA node emits a function value for MAP/BYROW/REDUCE/MAKEARRAY; non-parameter variables become captured inputs (the LET/closure equivalent). No recursion (a self-reference is a graph cycle) and no lambdas of lambdas" }],
  "list-cumulative": [{ excel: "SCAN", syntax: "=SCAN(init, array, LAMBDA(acc, x, ...))", parity: false, note: "Solenoid's Cumulative covers the fixed running ops (CumSum/CumMax/…); the SCAN node runs a running fold with an arbitrary formula, and REDUCE gives just the final value" }],
  "list-drop": [{ excel: "DROP", syntax: "=DROP(list, count)", parity: false, note: "The 1-D list spelling; DROP (table) is the 2-D rows+cols one" }],
  "list-filter": [{ excel: "FILTER", syntax: "=FILTER(array, include)", parity: false, note: "Conditions live on the card (extensible AND/OR rows) instead of an include vector; filtering by a PARALLEL list is the SUMIFS node or Frame from Lists → Frame Filter" }],
  "list-groupby": [{ excel: "GROUPBY", syntax: "=GROUPBY(row_fields, values, function)", parity: false, note: "1D parallel-list version: keys + values lists; 2D range grouping not supported" }],
  "list-index": [{ excel: "INDEX", syntax: "=INDEX(array, row)", parity: true }],
  "list-randarray": [{ excel: "RANDARRAY", syntax: "=RANDARRAY([rows],[cols],[min],[max],[integer])", parity: false, note: "1D list; re-rolls on recalc (F9)" }],
  "list-sequence": [{ excel: "SEQUENCE", syntax: "=SEQUENCE(rows, cols, start, step)", parity: false, note: "Solenoid's Range is 1D only; SEQUENCE can produce 2D arrays" }],
  "list-sort": [{ excel: "SORT", syntax: "=SORT(array, sort_index, order)", parity: false, note: "Solenoid sorts 1D lists only; Excel can sort multi-column ranges" }],
  "list-sortby": [{ excel: "SORTBY", syntax: "=SORTBY(array, by_array)", parity: false, note: "Sorts a 1-D array of ANY element type (text/date/… — the reorder is position-only) by a parallel NUMERIC key list; text sort keys aren't supported yet" }],
  "list-take": [{ excel: "TAKE", syntax: "=TAKE(list, count)", parity: false, note: "The 1-D list spelling; TAKE (table) is the 2-D rows+cols one" }],
  "list-unique": [{ excel: "UNIQUE", syntax: "=UNIQUE(array)", parity: true }],
  "vstack-table": [{ excel: "VSTACK", syntax: "=VSTACK(array1, array2, ...)", parity: true, note: "N-ary; ragged inputs pad with #N/A like Excel. A bare list counts as ONE ROW" }],
  "logest": [{ excel: "LOGEST", syntax: "=LOGEST(ys, xs)", parity: false, note: "Returns [m, b] as a list; Excel returns a full coefficient array" }],
  // Keys track the post-split catalog types (bool-*/if/not — the old multi-op
  // LogicalNode's "logic-*" keys went stale unnoticed until the drift test);
  // AND/OR/XOR are N-ary reducers now, so the "binary only" caveat is gone.
  "bool-and": [{ excel: "AND", syntax: "=AND(a, b, ...)", parity: true }],
  "if": [{ excel: "IF", syntax: "=IF(cond, a, b)", parity: true }],
  "not": [{ excel: "NOT", syntax: "=NOT(a)", parity: true }],
  "bool-or": [{ excel: "OR", syntax: "=OR(a, b, ...)", parity: true }],
  "bool-xor": [{ excel: "XOR", syntax: "=XOR(a, b, ...)", parity: true }],
  "lognormdist": [{ excel: "LOGNORM.DIST", syntax: "=LOGNORM.DIST(x, μ, σ, cum)" }],
  "lognorminv": [{ excel: "LOGNORM.INV", syntax: "=LOGNORM.INV(p, μ, σ)" }],
  "lookup-xlookup": [{ excel: "XLOOKUP", syntax: "=XLOOKUP(x, lookup, return)", parity: true }],
  "lookup-xmatch": [{ excel: "XMATCH", syntax: "=XMATCH(x, array, mode)", parity: false, note: "Modes 0 (exact), 1 (next larger), -1 (next smaller) supported; wildcard mode not supported" }],
  "make-array": [{ excel: "MAKEARRAY", syntax: "=MAKEARRAY(rows, cols, LAMBDA(r, c, ...))", parity: false, note: "MAKEARRAY node builds a grid from its own formula of (r, c), or a wired LAMBDA value" }],
  "map-table": [{ excel: "MAP", syntax: "=MAP(array1, [array2, ...], LAMBDA(x, ...))", parity: false, note: "MAP node zips up to three same-shape arrays through its own formula (x, y, z; a 1×1 broadcasts) or a wired LAMBDA value; Excel takes any number of arrays" }],
  "matdet-mdeterm": [{ excel: "MDETERM", syntax: "=MDETERM(array)", parity: false, note: "Square matrices only; uses LU decomposition with partial pivoting" }],
  "matdet-minverse": [{ excel: "MINVERSE", syntax: "=MINVERSE(array)", parity: false, note: "Square matrices only; returns null for singular matrices" }],
  "math-abs": [{ excel: "ABS", syntax: "=ABS(x)", parity: true }],
  "math-acos": [{ excel: "ACOS", syntax: "=ACOS(x)", parity: true }],
  "math-acosh": [{ excel: "ACOSH", syntax: "=ACOSH(x)", parity: true }],
  "math-acot": [{ excel: "ACOT", syntax: "=ACOT(x)", parity: true }],
  "math-acoth": [{ excel: "ACOTH", syntax: "=ACOTH(x)", parity: true }],
  "math-asin": [{ excel: "ASIN", syntax: "=ASIN(x)", parity: true }],
  "math-asinh": [{ excel: "ASINH", syntax: "=ASINH(x)", parity: true }],
  "math-atan": [{ excel: "ATAN", syntax: "=ATAN(x)", parity: true }],
  "math-atanh": [{ excel: "ATANH", syntax: "=ATANH(x)", parity: true }],
  "math-cos": [{ excel: "COS", syntax: "=COS(x)", parity: true }],
  "math-cosh": [{ excel: "COSH", syntax: "=COSH(x)", parity: true }],
  "math-cot": [{ excel: "COT", syntax: "=COT(x)", parity: true }],
  "math-coth": [{ excel: "COTH", syntax: "=COTH(x)", parity: true }],
  "math-csc": [{ excel: "CSC", syntax: "=CSC(x)", parity: true }],
  "math-csch": [{ excel: "CSCH", syntax: "=CSCH(x)", parity: true }],
  "math-erf": [
    { excel: "ERF", syntax: "=ERF(x)", parity: true },
    { excel: "ERF.PRECISE", syntax: "=ERF.PRECISE(x)", parity: true, note: "Same as ERF in Solenoid" },
  ],
  "math-erfc": [
    { excel: "ERFC", syntax: "=ERFC(x)", parity: true },
    { excel: "ERFC.PRECISE", syntax: "=ERFC.PRECISE(x)", parity: true, note: "Same as ERFC in Solenoid" },
  ],
  "math-even": [{ excel: "EVEN", syntax: "=EVEN(x)", parity: true }],
  "math-exp": [{ excel: "EXP", syntax: "=EXP(x)", parity: true }],
  "math-ceiling": [
    { excel: "CEILING.MATH", syntax: "=CEILING.MATH(x, sig)", parity: true, note: "Rounds toward +∞ to a multiple (the Multiple input); defaults to 1" },
    { excel: "CEILING", syntax: "=CEILING(x, significance)", parity: false, note: "Rounds toward +∞ like CEILING.MATH; Excel's CEILING rounds away from zero for negatives" },
  ],
  "math-floor": [
    { excel: "FLOOR.MATH", syntax: "=FLOOR.MATH(x, sig)", parity: true, note: "Rounds toward −∞ to a multiple (the Multiple input); defaults to 1" },
    { excel: "FLOOR", syntax: "=FLOOR(x, significance)", parity: false, note: "Rounds toward −∞ like FLOOR.MATH; Excel's FLOOR rounds toward zero for negatives" },
  ],
  "math-gamma": [{ excel: "GAMMA", syntax: "=GAMMA(x)" }],
  "math-gammaln": [
    { excel: "GAMMALN", syntax: "=GAMMALN(x)" },
    { excel: "GAMMALN.PRECISE", syntax: "=GAMMALN.PRECISE(x)" },
  ],
  "math-gauss": [{ excel: "GAUSS", syntax: "=GAUSS(x)", parity: true }],
  "math-int": [{ excel: "INT", syntax: "=INT(x)", parity: true }],
  "iseven-isodd": [
    { excel: "ISEVEN", syntax: "=ISEVEN(x)", parity: true, note: "Pick ISEVEN/ISODD in the node; emits a logical (TRUE/FALSE), broadcasts over a list" },
    { excel: "ISODD", syntax: "=ISODD(x)", parity: true, note: "Pick ISEVEN/ISODD in the node; emits a logical (TRUE/FALSE), broadcasts over a list" },
  ],
  "math-log": [{ excel: "LN", syntax: "=LN(x)", parity: true }],
  "math-log10": [{ excel: "LOG10", syntax: "=LOG10(x)", parity: true }],
  "math-mround": [{ excel: "MROUND", syntax: "=MROUND(x, multiple)", parity: true }],
  "math-odd": [{ excel: "ODD", syntax: "=ODD(x)", parity: true }],
  "math-phi": [{ excel: "PHI", syntax: "=PHI(x)", parity: true }],
  "math-sec": [{ excel: "SEC", syntax: "=SEC(x)", parity: true }],
  "math-sech": [{ excel: "SECH", syntax: "=SECH(x)", parity: true }],
  "math-sign": [{ excel: "SIGN", syntax: "=SIGN(x)", parity: true }],
  "math-sin": [{ excel: "SIN", syntax: "=SIN(x)", parity: true }],
  "math-sinh": [{ excel: "SINH", syntax: "=SINH(x)", parity: true }],
  "math-sqrt": [{ excel: "SQRT", syntax: "=SQRT(x)", parity: true }],
  "math-sqrtpi": [{ excel: "SQRTPI", syntax: "=SQRTPI(x)", parity: true }],
  "math-tan": [{ excel: "TAN", syntax: "=TAN(x)", parity: true }],
  "math-tanh": [{ excel: "TANH", syntax: "=TANH(x)", parity: true }],
  "math-trunc": [{ excel: "TRUNC", syntax: "=TRUNC(x)", parity: true }],
  "mirr": [{ excel: "MIRR", syntax: "=MIRR(flows, fin_rate, reinv_rate)", parity: true }],
  "mode": [{ excel: "MODE.SNGL", syntax: "=MODE.SNGL(range)", parity: true }],
  "mode-mult": [{ excel: "MODE.MULT", syntax: "=MODE.MULT(range)" }],
  "multinomial": [{ excel: "MULTINOMIAL", syntax: "=MULTINOMIAL(n1, n2, ...)", parity: true }],
  "na": [{ excel: "NA", syntax: "=NA()", parity: true }],
  "negbinomdist": [{ excel: "NEGBINOM.DIST", syntax: "=NEGBINOM.DIST(k, r, p, cum)" }],
  "normdist": [{ excel: "NORM.DIST", syntax: "=NORM.DIST(x, μ, σ, cum)", parity: true }],
  "norminv": [{ excel: "NORM.INV", syntax: "=NORM.INV(p, μ, σ)", parity: true }],
  "normsdist": [{ excel: "NORM.S.DIST", syntax: "=NORM.S.DIST(z, cum)", parity: true }],
  "normsinv": [{ excel: "NORM.S.INV", syntax: "=NORM.S.INV(p)", parity: true }],
  "npv": [{ excel: "NPV", syntax: "=NPV(rate, v1, v2, ...)", parity: true }],
  "nth-large": [{ excel: "LARGE", syntax: "=LARGE(array, k)", parity: true }],
  "nth-small": [{ excel: "SMALL", syntax: "=SMALL(array, k)", parity: true }],
  "oddcoupon-oddfprice": [{ excel: "ODDFPRICE", syntax: "=ODDFPRICE(...)", parity: false, note: "30/360 basis only; other basis values not supported" }],
  "oddcoupon-oddfyield": [{ excel: "ODDFYIELD", syntax: "=ODDFYIELD(...)", parity: false, note: "30/360 basis only" }],
  "oddcoupon-oddlprice": [{ excel: "ODDLPRICE", syntax: "=ODDLPRICE(...)", parity: false, note: "30/360 basis only" }],
  "oddcoupon-oddlyield": [{ excel: "ODDLYIELD", syntax: "=ODDLYIELD(...)", parity: false, note: "30/360 basis only" }],

  "poissondist": [{ excel: "POISSON.DIST", syntax: "=POISSON.DIST(k, λ, cum)" }],
  "pricedisc-pricedisc": [{ excel: "PRICEDISC", syntax: "=PRICEDISC(settle,maturity,discount,redemption)", parity: false, note: "Discount bond price; not yet supported" }],
  "pricedisc-yielddisc": [{ excel: "YIELDDISC", syntax: "=YIELDDISC(settle,maturity,pr,redemption)", parity: false, note: "Discount bond yield; not yet supported" }],
  "pricemat-pricemat": [{ excel: "PRICEMAT", syntax: "=PRICEMAT(settle,maturity,issue,rate,yld)", parity: false, note: "Maturity-pay bond price; not yet supported" }],
  "pricemat-yieldmat": [{ excel: "YIELDMAT", syntax: "=YIELDMAT(settle,maturity,issue,rate,pr)", parity: false, note: "Annual yield at maturity; not yet supported" }],
  "prob": [{ excel: "PROB", syntax: "=PROB(range, prob, lo, hi)" }],
  "randbetween": [
    { excel: "RAND", syntax: "=RAND()", parity: true },
    { excel: "RANDBETWEEN", syntax: "=RANDBETWEEN(bot, top)", parity: false, note: "Solenoid returns a float; Excel returns an integer" },
  ],
  "rank-avg": [{ excel: "RANK.AVG", syntax: "=RANK.AVG(x, array)", parity: true }],
  "rank-eq": [{ excel: "RANK.EQ", syntax: "=RANK.EQ(x, array)", parity: true }],

  "reduce-avedev": [{ excel: "AVEDEV", syntax: "=AVEDEV(range)", parity: true }],
  "reduce-avg": [
    { excel: "AVERAGE", syntax: "=AVERAGE(range)", parity: true },
    { excel: "AVERAGEA", syntax: "=AVERAGEA(range)", parity: false, note: "AVERAGEA counts text as 0; Solenoid is numbers-only" },
  ],
  "reduce-count": [
    { excel: "COUNT", syntax: "=COUNT(range)", parity: true },
    { excel: "COUNTA", syntax: "=COUNTA(range)", parity: false, note: "COUNTA counts non-empty cells; Solenoid is numbers-only" },
  ],
  "reduce-devsq": [{ excel: "DEVSQ", syntax: "=DEVSQ(range)", parity: true }],
  "reduce-geomean": [{ excel: "GEOMEAN", syntax: "=GEOMEAN(range)", parity: true }],
  "reduce-harmean": [{ excel: "HARMEAN", syntax: "=HARMEAN(range)", parity: true }],
  "reduce-kurt": [{ excel: "KURT", syntax: "=KURT(range)", parity: true }],
  "reduce-lambda": [{ excel: "REDUCE", syntax: "=REDUCE(init, array, LAMBDA(acc, x, ...))", parity: false, note: "REDUCE node folds with its own formula of (acc, x), or a wired LAMBDA value" }],
  "scan-lambda": [{ excel: "SCAN", syntax: "=SCAN(init, array, LAMBDA(acc, x, ...))", parity: false, note: "SCAN node folds like REDUCE but emits every running accumulator, same shape as the input, with its own formula of (acc, x) or a wired LAMBDA value" }],
  "reduce-max": [
    { excel: "MAX", syntax: "=MAX(range)", parity: true },
    { excel: "MAXA", syntax: "=MAXA(range)", parity: false, note: "MAXA counts text as 0; Solenoid is numbers-only" },
  ],
  "reduce-median": [{ excel: "MEDIAN", syntax: "=MEDIAN(range)", parity: true }],
  "reduce-min": [
    { excel: "MIN", syntax: "=MIN(range)", parity: true },
    { excel: "MINA", syntax: "=MINA(range)", parity: false, note: "MINA counts text as 0; Solenoid is numbers-only" },
  ],
  "reduce-product": [{ excel: "PRODUCT", syntax: "=PRODUCT(n1, n2, ...)", parity: false, note: "Solenoid takes a single list input; build list first with List node" }],
  "reduce-skew": [{ excel: "SKEW", syntax: "=SKEW(range)", parity: true }],
  "reduce-skew_p": [{ excel: "SKEW.P", syntax: "=SKEW.P(range)", parity: true }],
  "reduce-stdev": [
    { excel: "STDEV.S", syntax: "=STDEV.S(range)", parity: true },
    { excel: "STDEVA", syntax: "=STDEVA(range)", parity: false, note: "STDEVA counts text as 0; Solenoid is numbers-only" },
  ],
  "reduce-stdev_p": [
    { excel: "STDEV.P", syntax: "=STDEV.P(range)", parity: true },
    { excel: "STDEVPA", syntax: "=STDEVPA(range)", parity: false, note: "STDEVPA counts text as 0; Solenoid is numbers-only" },
  ],
  "reduce-sum": [{ excel: "SUM", syntax: "=SUM(range)", parity: true }],
  "reduce-sumsq": [{ excel: "SUMSQ", syntax: "=SUMSQ(n1, n2, ...)", parity: false, note: "Solenoid takes a list input; build list first" }],
  "reduce-var_p": [
    { excel: "VAR.P", syntax: "=VAR.P(range)", parity: true },
    { excel: "VARPA", syntax: "=VARPA(range)", parity: false, note: "VARPA counts text as 0; Solenoid is numbers-only" },
  ],
  "reduce-var_s": [
    { excel: "VAR.S", syntax: "=VAR.S(range)", parity: true },
    { excel: "VARA", syntax: "=VARA(range)", parity: false, note: "VARA counts text as 0; Solenoid is numbers-only" },
  ],
  "regex": [
    { excel: "REGEXTEST", syntax: "=REGEXTEST(text, pattern)", parity: false, note: "Returns 1/0; use Regex node with REGEXTEST op" },
    { excel: "REGEXEXTRACT", syntax: "=REGEXEXTRACT(text, pattern, [return_all])", parity: false, note: "First match or all matches; use Regex node with REGEXEXTRACT op" },
    { excel: "REGEXREPLACE", syntax: "=REGEXREPLACE(text, pattern, replacement)", parity: false, note: "Global replace by default; use Regex node with REGEXREPLACE op" },
  ],
  "regression-steyx": [{ excel: "STEYX", syntax: "=STEYX(ys, xs)", parity: true }],
  "reshape-tocol": [{ excel: "TOCOL", syntax: "=TOCOL(array)", parity: false, note: "ignore_empty and scan_by_column flags not supported" }],
  "reshape-torow": [{ excel: "TOROW", syntax: "=TOROW(array)", parity: false, note: "ignore_empty flag not supported" }],
  "reshape-wrapcols": [{ excel: "WRAPCOLS", syntax: "=WRAPCOLS(vector, rows)", parity: false, note: "Pads with #N/A (Excel's default); a custom pad_with is not supported" }],
  "reshape-wraprows": [{ excel: "WRAPROWS", syntax: "=WRAPROWS(vector, cols)", parity: false, note: "Pads with #N/A (Excel's default); a custom pad_with is not supported" }],
  "roman-arabic-arabic": [{ excel: "ARABIC", syntax: "=ARABIC(text)", parity: false, note: "Roman numeral string → integer" }],
  "roman-arabic-roman": [{ excel: "ROMAN", syntax: "=ROMAN(n)", parity: false, note: "Integer (1–3999) → Roman numeral string" }],
  "roundn-dir": [
    { excel: "ROUNDDOWN", syntax: "=ROUNDDOWN(x, digits)", parity: true },
    { excel: "ROUNDUP", syntax: "=ROUNDUP(x, digits)", parity: true },
  ],
  "roundn-round": [{ excel: "ROUND", syntax: "=ROUND(x, digits)", parity: true }],

  "secdesc-disc": [{ excel: "DISC", syntax: "=DISC(settle,maturity,pr,redemption)", parity: false, note: "Discount rate; not yet supported" }],
  "secdesc-intrate": [{ excel: "INTRATE", syntax: "=INTRATE(settle,maturity,invest,redemption)", parity: false, note: "Interest rate for fully invested security; not yet supported" }],
  "secdesc-received": [{ excel: "RECEIVED", syntax: "=RECEIVED(settle,maturity,invest,discount)", parity: false, note: "Amount received at maturity; not yet supported" }],
  "seriessum": [{ excel: "SERIESSUM", syntax: "=SERIESSUM(x, n, m, coef)", parity: true }],
  "sp-sumproduct": [{ excel: "SUMPRODUCT", syntax: "=SUMPRODUCT(a, b)", parity: false, note: "Solenoid takes exactly two list inputs (no 3+ arrays)" }],
  "sp-sumx2my2": [{ excel: "SUMX2MY2", syntax: "=SUMX2MY2(x, y)", parity: true }],
  "sp-sumx2py2": [{ excel: "SUMX2PY2", syntax: "=SUMX2PY2(x, y)", parity: true }],
  "sp-sumxmy2": [{ excel: "SUMXMY2", syntax: "=SUMXMY2(x, y)", parity: true }],
  "stat-percentile": [
    { excel: "PERCENTILE.EXC", syntax: "=PERCENTILE.EXC(array, k)", parity: true },
    { excel: "PERCENTILE.INC", syntax: "=PERCENTILE.INC(array, k)", parity: true },
  ],
  "stat-percentrank": [
    { excel: "PERCENTRANK.EXC", syntax: "=PERCENTRANK.EXC(array, x)", parity: true },
    { excel: "PERCENTRANK.INC", syntax: "=PERCENTRANK.INC(array, x)", parity: true },
  ],
  "stat-quartile": [
    { excel: "QUARTILE.EXC", syntax: "=QUARTILE.EXC(array, q)", parity: true },
    { excel: "QUARTILE.INC", syntax: "=QUARTILE.INC(array, q)", parity: true },
  ],
  "stat-standardize": [{ excel: "STANDARDIZE", syntax: "=STANDARDIZE(x, μ, σ)", parity: true }],
  "switch": [{ excel: "SWITCH", syntax: "=SWITCH(expr, w1, t1, ...)", parity: false, note: "Fixed 3 cases; Excel is variadic" }],
  "t-test-equal-var": [{ excel: "T.TEST", syntax: "=T.TEST(a, b, tails, type)", parity: false, note: "2-tailed only; for 1-tailed divide result by 2" }],
  "table-info": [
    { excel: "COLUMNS", syntax: "=COLUMNS(array)", parity: false, note: "Works on table socket; use List → Length node for 1D lists" },
    { excel: "ROWS", syntax: "=ROWS(array)", parity: false, note: "Works on table socket; use List → Length node for 1D lists" },
  ],
  "table-mult": [{ excel: "MMULT", syntax: "=MMULT(a, b)", parity: false, note: "A columns must equal B rows" }],
  "table-transpose": [{ excel: "TRANSPOSE", syntax: "=TRANSPOSE(array)", parity: false }],
  "table-unit": [{ excel: "MUNIT", syntax: "=MUNIT(n)", parity: false }],
  "tbill-tbilleq": [{ excel: "TBILLEQ", syntax: "=TBILLEQ(settle,maturity,discount)", parity: false, note: "T-bill bond-equivalent yield; not yet supported" }],
  "tbill-tbillprice": [{ excel: "TBILLPRICE", syntax: "=TBILLPRICE(settle,maturity,discount)", parity: false, note: "T-bill price; not yet supported" }],
  "tbill-tbillyield": [{ excel: "TBILLYIELD", syntax: "=TBILLYIELD(settle,maturity,pr)", parity: false, note: "T-bill yield; not yet supported" }],
  "tblsel-choosecols": [{ excel: "CHOOSECOLS", syntax: "=CHOOSECOLS(array, col1, col2, ...)", parity: false, note: "Takes a list of indices; negative indices count from end" }],
  "tblsel-chooserows": [{ excel: "CHOOSEROWS", syntax: "=CHOOSEROWS(array, row1, row2, ...)", parity: false, note: "Takes a list of indices; negative indices count from end" }],
  "tdist": [
    { excel: "T.DIST", syntax: "=T.DIST(x, df, cum)", parity: true },
    { excel: "T.DIST.2T", syntax: "=T.DIST.2T(x, df)", parity: true },
    { excel: "T.DIST.RT", syntax: "=T.DIST.RT(x, df)", parity: true },
  ],
  "text-after-before-after": [{ excel: "TEXTAFTER", syntax: "=TEXTAFTER(text, delimiter)", parity: false, note: "First occurrence only; instance_num and match_mode not supported" }],
  "text-after-before-before": [{ excel: "TEXTBEFORE", syntax: "=TEXTBEFORE(text, delimiter)", parity: false, note: "First occurrence only; instance_num and match_mode not supported" }],
  "text-clean": [{ excel: "CLEAN", syntax: "=CLEAN(text)", parity: false }],
  "text-concat": [
    { excel: "CONCAT", syntax: "=CONCAT(text1, text2, ...)", parity: false, note: "Fixed 4 inputs; chain Concat nodes for more" },
    { excel: "CONCATENATE", syntax: "=CONCATENATE(text1, ...)", parity: false, note: "Fixed 4 inputs; chain Concat nodes for more" },
  ],
  "text-dollar": [{ excel: "DOLLAR", syntax: "=DOLLAR(number)", parity: false, note: "Formats as \"$1,234.56\" — optional decimals input" }],
  "text-exact": [{ excel: "EXACT", syntax: "=EXACT(text1, text2)", parity: false }],
  "text-find-find": [
    { excel: "FIND", syntax: "=FIND(find_text, within)", parity: false },
    { excel: "FINDB", syntax: "=FINDB(find_text, within)", parity: false, note: "Byte-indexed; treated as character-indexed" },
  ],
  "text-find-search": [
    { excel: "SEARCH", syntax: "=SEARCH(find_text, within)", parity: false },
    { excel: "SEARCHB", syntax: "=SEARCHB(find_text, within)", parity: false, note: "Byte-indexed; treated as character-indexed" },
  ],
  "text-fixed": [{ excel: "FIXED", syntax: "=FIXED(number, decimals)", parity: false, note: "Use TEXT node with \"0.00\" format" }],
  "text-join": [{ excel: "TEXTJOIN", syntax: "=TEXTJOIN(delim, ignore, ...)", parity: false, note: "Takes a strlist input — wire from TEXTSPLIT or a Text Input list" }],
  "text-left": [
    { excel: "LEFT", syntax: "=LEFT(text, chars)", parity: false },
    { excel: "LEFTB", syntax: "=LEFTB(text, bytes)", parity: false, note: "Byte-indexed; treated as character-indexed" },
  ],
  "text-len": [
    { excel: "LEN", syntax: "=LEN(text)", parity: false },
    { excel: "LENB", syntax: "=LENB(text)", parity: false, note: "Byte-indexed; treated as character-indexed" },
  ],
  "text-lower": [{ excel: "LOWER", syntax: "=LOWER(text)", parity: false }],
  "text-mid": [
    { excel: "MID", syntax: "=MID(text, start, chars)", parity: false },
    { excel: "MIDB", syntax: "=MIDB(text, start, bytes)", parity: false, note: "Byte-indexed; treated as character-indexed" },
  ],
  // TEXT / VALUE / VALUETOTEXT live on Cast now (their dedicated nodes are
  // deprecated — hidden from the menu, load-only).
  "cast": [
    { excel: "TEXT", syntax: "=TEXT(value, format)", parity: false, note: "Cast to Text with a format — simplified formats: \"\", \"0\", \"0.00\", \"0.00%\"; date patterns (YYYY-MM-DD) for date sources" },
    { excel: "VALUE", syntax: "=VALUE(text)", parity: false, note: "Cast to Number" },
    { excel: "VALUETOTEXT", syntax: "=VALUETOTEXT(value)", parity: false, note: "Cast to Text with an empty format — default string conversion" },
  ],
  "text-numbervalue": [{ excel: "NUMBERVALUE", syntax: "=NUMBERVALUE(text)", parity: false, note: "Custom decimal/group separators; for plain parsing use Cast to Number" }],
  "text-proper": [{ excel: "PROPER", syntax: "=PROPER(text)", parity: false }],
  "text-replace": [
    { excel: "REPLACE", syntax: "=REPLACE(text, start, n, new)", parity: false },
    { excel: "REPLACEB", syntax: "=REPLACEB(text, start, b, new)", parity: false, note: "Byte-indexed; treated as character-indexed" },
  ],
  "text-rept": [{ excel: "REPT", syntax: "=REPT(text, n)", parity: false }],
  "text-right": [
    { excel: "RIGHT", syntax: "=RIGHT(text, chars)", parity: false },
    { excel: "RIGHTB", syntax: "=RIGHTB(text, bytes)", parity: false, note: "Byte-indexed; treated as character-indexed" },
  ],
  "text-split": [
    { excel: "TEXTSPLIT", syntax: "=TEXTSPLIT(text, delim)", parity: false, note: "Outputs a strlist; row/col delimiter pair not supported" },
    { excel: "TEXTSPLIT", syntax: "=TEXTSPLIT(text, delim)", parity: false, note: "Row/col delimiter pair not supported; outputs a strlist" },
  ],
  "text-substitute": [{ excel: "SUBSTITUTE", syntax: "=SUBSTITUTE(text, old, new)", parity: false, note: "Instance number not supported; replaces all" }],
  "text-trim": [{ excel: "TRIM", syntax: "=TRIM(text)", parity: false }],
  "text-upper": [{ excel: "UPPER", syntax: "=UPPER(text)", parity: false }],
  "time-value": [{ excel: "TIMEVALUE", syntax: "=TIMEVALUE(time_text)", parity: false, note: "Parses HH:MM:SS format" }],
  "tinv": [
    { excel: "T.INV", syntax: "=T.INV(p, df)", parity: true },
    { excel: "T.INV.2T", syntax: "=T.INV.2T(p, df)", parity: true },
  ],
  "trend": [{ excel: "TREND", syntax: "=TREND(ys, xs, new_xs)", parity: false, note: "Linear only; new_xs required (Excel makes it optional)" }],
  "trimmean": [{ excel: "TRIMMEAN", syntax: "=TRIMMEAN(range, pct)", parity: true }],
  "sumifs": [
    { excel: "SUMIFS", syntax: "=SUMIFS(sum_range, criteria_range1, criteria1, ...)", parity: true, note: "Takes one frame: ranges are named columns; criteria are op + value rows instead of criteria strings (\">10\")" },
    { excel: "SUMIF", syntax: "=SUMIF(range, criteria, [sum_range])", parity: true },
    { excel: "COUNTIFS", syntax: "=COUNTIFS(criteria_range1, criteria1, ...)", parity: true },
    { excel: "COUNTIF", syntax: "=COUNTIF(range, criteria)", parity: true },
    { excel: "AVERAGEIFS", syntax: "=AVERAGEIFS(average_range, criteria_range1, criteria1, ...)", parity: true },
    { excel: "AVERAGEIF", syntax: "=AVERAGEIF(range, criteria, [average_range])", parity: true },
    { excel: "MINIFS", syntax: "=MINIFS(min_range, criteria_range1, criteria1, ...)", parity: true },
    { excel: "MAXIFS", syntax: "=MAXIFS(max_range, criteria_range1, criteria1, ...)", parity: true },
  ],
  "tbltd-take": [{ excel: "TAKE", syntax: "=TAKE(array, rows, [cols])", parity: true, note: "Negative counts take from the end; 0 stands in for an omitted argument" }],
  "tbltd-drop": [{ excel: "DROP", syntax: "=DROP(array, rows, [cols])", parity: true, note: "Negative counts drop from the end; 0 stands in for an omitted argument" }],
  "table-expand": [{ excel: "EXPAND", syntax: "=EXPAND(array, rows, [cols], [pad_with])", parity: true, note: "Unwired Fill pads with #N/A, Excel's default" }],
  "tvm": [
    { excel: "PMT", syntax: "=PMT(rate, nper, pv)", parity: true, note: "One acausal TVM node: leave pmt unwired and it solves" },
    { excel: "PV", syntax: "=PV(rate, nper, pmt, fv)", parity: true, note: "Leave pv unwired" },
    { excel: "FV", syntax: "=FV(rate, nper, pmt, pv)", parity: true, note: "Leave fv unwired" },
    { excel: "NPER", syntax: "=NPER(rate, pmt, pv)", parity: true, note: "Leave nper unwired" },
    { excel: "RATE", syntax: "=RATE(nper, pmt, pv)", parity: true, note: "Leave rate unwired; no guess needed" },
  ],
  "twomath-atan2": [{ excel: "ATAN2", syntax: "=ATAN2(x, y)", parity: true }],
  "twomath-delta": [{ excel: "DELTA", syntax: "=DELTA(a, b)", parity: true }],
  "twomath-gestep": [{ excel: "GESTEP", syntax: "=GESTEP(a, step)", parity: true }],
  "twomath-log": [{ excel: "LOG", syntax: "=LOG(x, base)", parity: true }],
  "url-encode": [{ excel: "ENCODEURL", syntax: "=ENCODEURL(text)", parity: false, note: "Not yet supported" }],
  "vdb": [{ excel: "VDB", syntax: "=VDB(cost,salv,life,start,end,[factor])", note: "factor defaults to 2 (DDB); no_switch flag not exposed" }],
  "weibulldist": [{ excel: "WEIBULL.DIST", syntax: "=WEIBULL.DIST(x, α, β, cum)" }],
  "xirr": [{ excel: "XIRR", syntax: "=XIRR(flows, dates)", parity: false, note: "Dates as serials (wire from date nodes); guess parameter not supported" }],
  "xnpv": [{ excel: "XNPV", syntax: "=XNPV(rate, flows, dates)", parity: false, note: "Date-based NPV; not yet supported" }],
  "z-test": [{ excel: "Z.TEST", syntax: "=Z.TEST(array, μ, σ)", parity: false, note: "σ is optional; if omitted uses sample stdev (Excel behavior matches)" }],
};

export interface ExcelGapRow {
  excel: string;
  syntax: string;
  category: string;
  oos?: boolean;   // intentionally out of scope (cell refs, OLAP, superseded classics)
  composition?: boolean; // no single node, but achievable by composing nodes (Filter → Aggregate, …)
  note?: string;
}

/** Excel functions with no Solenoid node. Self-heals: the reference drops any
 *  entry whose name later becomes node-backed. */
export const EXCEL_GAP: ExcelGapRow[] = [
  { excel: "SUBTOTAL", syntax: "=SUBTOTAL(fn, range)", category: "Math & Trig", composition: true, note: "Use Aggregate with the matching op; hidden-row exclusion (101–111 variants) not applicable in a node graph" },
  { excel: "SUMIF", syntax: "=SUMIF(range, crit)", category: "Math & Trig", composition: true, note: "Compose Filter → Aggregate (SUM)" },
  { excel: "SUMIFS", syntax: "=SUMIFS(range, crit, ...)", category: "Math & Trig", composition: true, note: "Chain multiple Filter nodes, then Aggregate (SUM)" },
  { excel: "AVERAGEIF", syntax: "=AVERAGEIF(range, crit)", category: "Statistics", composition: true, note: "Compose Filter → Aggregate (AVERAGE)" },
  { excel: "AVERAGEIFS", syntax: "=AVERAGEIFS(range, crit, ...)", category: "Statistics", composition: true, note: "Chain multiple Filter nodes" },
  { excel: "COUNTBLANK", syntax: "=COUNTBLANK(range)", category: "Statistics", oos: true, note: "Counts empty cells; not applicable in node graph" },
  { excel: "COUNTIF", syntax: "=COUNTIF(range, crit)", category: "Statistics", composition: true, note: "Compose Filter → Aggregate (COUNT)" },
  { excel: "COUNTIFS", syntax: "=COUNTIFS(range, crit, ...)", category: "Statistics", composition: true, note: "Chain multiple Filter nodes" },
  { excel: "MAXIFS", syntax: "=MAXIFS(range, crit, ...)", category: "Statistics", composition: true, note: "Compose Filter → Aggregate (MAX)" },
  { excel: "MINIFS", syntax: "=MINIFS(range, crit, ...)", category: "Statistics", composition: true, note: "Compose Filter → Aggregate (MIN)" },
  { excel: "ADDRESS", syntax: "=ADDRESS(row, col)", category: "Lookup & Reference", oos: true, note: "Returns a cell reference as text; out of scope" },
  { excel: "AREAS", syntax: "=AREAS(reference)", category: "Lookup & Reference", oos: true, note: "Count areas in reference; out of scope" },
  { excel: "COLUMN", syntax: "=COLUMN(reference)", category: "Lookup & Reference", oos: true, note: "Returns column number; out of scope" },
  { excel: "FORMULATEXT", syntax: "=FORMULATEXT(reference)", category: "Lookup & Reference", oos: true, note: "Returns formula as text; out of scope" },
  { excel: "GETPIVOTDATA", syntax: "=GETPIVOTDATA(field, pivot, ...)", category: "Lookup & Reference", oos: true, note: "PivotTable data extraction; out of scope" },
  { excel: "HLOOKUP", syntax: "=HLOOKUP(x, table, row)", category: "Lookup & Reference", oos: true, note: "Superseded by XLOOKUP" },
  { excel: "HYPERLINK", syntax: "=HYPERLINK(url, text)", category: "Lookup & Reference", oos: true, note: "Creates a clickable link; out of scope" },
  { excel: "INDIRECT", syntax: "=INDIRECT(ref_text)", category: "Lookup & Reference", oos: true, note: "Evaluates a text string as a cell reference; out of scope" },
  { excel: "LOOKUP", syntax: "=LOOKUP(x, lookup_vector, result)", category: "Lookup & Reference", oos: true, note: "Superseded by XLOOKUP" },
  { excel: "MATCH", syntax: "=MATCH(x, array, type)", category: "Lookup & Reference", oos: true, note: "Superseded by XMATCH" },
  { excel: "OFFSET", syntax: "=OFFSET(ref, rows, cols)", category: "Lookup & Reference", oos: true, note: "Returns reference offset from a cell; out of scope" },
  { excel: "ROW", syntax: "=ROW(reference)", category: "Lookup & Reference", oos: true, note: "Returns row number; out of scope" },
  { excel: "RTD", syntax: "=RTD(prog_id, server, ...)", category: "Lookup & Reference", oos: true, note: "Real-time data from COM server; out of scope" },
  { excel: "VLOOKUP", syntax: "=VLOOKUP(x, table, col)", category: "Lookup & Reference", oos: true, note: "Superseded by XLOOKUP" },
  { excel: "CELL", syntax: "=CELL(info_type, ref)", category: "Info", oos: true, note: "Cell metadata; out of scope" },
  { excel: "ERROR.TYPE", syntax: "=ERROR.TYPE(error_val)", category: "Info", oos: true, note: "Excel error-type enum; no cell-error model in a node graph" },
  { excel: "INFO", syntax: "=INFO(type_text)", category: "Info", oos: true, note: "Environment info; out of scope" },
  { excel: "ISFORMULA", syntax: "=ISFORMULA(ref)", category: "Info", oos: true, note: "Cell formula check; out of scope" },
  { excel: "ISREF", syntax: "=ISREF(v)", category: "Info", oos: true, note: "Cell reference check; out of scope" },
  { excel: "SHEET", syntax: "=SHEET(value)", category: "Info", oos: true, note: "Sheet index; out of scope" },
  { excel: "SHEETS", syntax: "=SHEETS(reference)", category: "Info", oos: true, note: "Sheet count; out of scope" },
  { excel: "FILTERXML", syntax: "=FILTERXML(xml, xpath)", category: "Web & Cube", oos: true, note: "XML scraping; out of scope" },
  { excel: "WEBSERVICE", syntax: "=WEBSERVICE(url)", category: "Web & Cube", oos: true, note: "Live web fetch; out of scope" },
  { excel: "CUBEKPIMEMBER", syntax: "=CUBEKPIMEMBER(...)", category: "Web & Cube", oos: true, note: "OLAP cube; out of scope" },
  { excel: "CUBEMEMBER", syntax: "=CUBEMEMBER(connection, expr)", category: "Web & Cube", oos: true, note: "OLAP cube; out of scope" },
  { excel: "CUBEMEMBERPROPERTY", syntax: "=CUBEMEMBERPROPERTY(...)", category: "Web & Cube", oos: true, note: "OLAP cube; out of scope" },
  { excel: "CUBERANKEDMEMBER", syntax: "=CUBERANKEDMEMBER(...)", category: "Web & Cube", oos: true, note: "OLAP cube; out of scope" },
  { excel: "CUBESET", syntax: "=CUBESET(connection, set_expr)", category: "Web & Cube", oos: true, note: "OLAP cube; out of scope" },
  { excel: "CUBESETCOUNT", syntax: "=CUBESETCOUNT(set)", category: "Web & Cube", oos: true, note: "OLAP cube; out of scope" },
  { excel: "CUBEVALUE", syntax: "=CUBEVALUE(connection, ...)", category: "Web & Cube", oos: true, note: "OLAP cube; out of scope" },
  { excel: "ASC", syntax: "=ASC(text)", category: "Text", oos: true, note: "East Asian full-width to half-width; out of scope" },
  { excel: "BAHTTEXT", syntax: "=BAHTTEXT(number)", category: "Text", oos: true, note: "Thai currency text; out of scope" },
  { excel: "DBCS", syntax: "=DBCS(text)", category: "Text", oos: true, note: "East Asian half-width to full-width; out of scope" },
  { excel: "PHONETIC", syntax: "=PHONETIC(reference)", category: "Text", oos: true, note: "Japanese phonetic; out of scope" },
  { excel: "DAVERAGE", syntax: "=DAVERAGE(db, field, criteria)", category: "Database", composition: true, note: "Compose Filter → Aggregate (AVERAGE)" },
  { excel: "DCOUNT", syntax: "=DCOUNT(db, field, criteria)", category: "Database", composition: true, note: "Compose Filter → Aggregate (COUNT)" },
  { excel: "DCOUNTA", syntax: "=DCOUNTA(db, field, criteria)", category: "Database", composition: true, note: "Compose Filter → Aggregate (COUNT)" },
  { excel: "DGET", syntax: "=DGET(db, field, criteria)", category: "Database", composition: true, note: "Use XLOOKUP on the relevant column — DGET's 'unique match only' behavior is an Excel artifact; not a separate node" },
  { excel: "DMAX", syntax: "=DMAX(db, field, criteria)", category: "Database", composition: true, note: "Compose Filter → Aggregate (MAX)" },
  { excel: "DMIN", syntax: "=DMIN(db, field, criteria)", category: "Database", composition: true, note: "Compose Filter → Aggregate (MIN)" },
  { excel: "DPRODUCT", syntax: "=DPRODUCT(db, field, criteria)", category: "Database", composition: true, note: "Compose Filter → Aggregate (PRODUCT)" },
  { excel: "DSTDEV", syntax: "=DSTDEV(db, field, criteria)", category: "Database", composition: true, note: "Compose Filter → Aggregate (STDEV.S)" },
  { excel: "DSTDEVP", syntax: "=DSTDEVP(db, field, criteria)", category: "Database", composition: true, note: "Compose Filter → Aggregate (STDEV.P)" },
  { excel: "DSUM", syntax: "=DSUM(db, field, criteria)", category: "Database", composition: true, note: "Compose Filter → Aggregate (SUM)" },
  { excel: "DVAR", syntax: "=DVAR(db, field, criteria)", category: "Database", composition: true, note: "Compose Filter → Aggregate (VAR.S)" },
  { excel: "DVARP", syntax: "=DVARP(db, field, criteria)", category: "Database", composition: true, note: "Compose Filter → Aggregate (VAR.P)" },
  { excel: "LET", syntax: "=LET(name, value, ...)", category: "Excel 365", oos: true, note: "Node-graph wiring is the equivalent of named intermediate values" },
];
