// Maps every node class to its React component. Add one row when adding a node.
// Imported by Canvas.tsx; kept separate so agents edit this file, not the full canvas.

import { ClassicPreset } from "rete";
import type { JSXElementConstructor } from "react";
import type { RenderEmit } from "rete-react-plugin";
import type { Schemes } from "./schemes";
import {
  AngleDialNode, SlicerNode, CableSwitchNode, NoteNode, ReportNode, SessionHistoryNode, PresentationNode, ImageNode,
  SparklineNode, ChartNode, HistogramNode, KpiNode, BulletNode, TreemapNode, SankeyNode, MermaidNode, GaugeNode, HeatmapCellNode, ChartBuilderNode, DatePickerNode, DateRangeNode, XYPadNode,
  NumberInputNode, ArithmeticNode, DisplayNode, ComparisonNode, MathFnNode,
  ColorPickerNode,
  ClampNode, BooleanOpNode, NotNode, IfNode, ConduitNode, CastNode, ConstantNode, MRoundNode,
  ListInputNode, AggregateNode, RangeNode, ListLengthNode, ListIndexNode,
  SortNode, ReverseNode, SliceNode, FilterNode, FillNode, XLookupNode,
  GcdNode, IFErrorNode, RandBetweenNode, RoundNNode, ConvertNode,
  UniqueNode, SetOpNode, SetRelationNode, TakeNode, DropNode, VStackNode, CumulativeNode, DiffNode,
  ArgMinMaxNode, ContainsNode, NthValueNode, PercentileNode, QuartileNode,
  PercentrankNode, RankNode, CorrelNode, BesselNode, CombinatoricsNode, TwoInputMathNode,
  SumProductNode, ChooseNode, BooleanInputNode, SliderInputNode, IsTestNode,
  NaNode, AlertNode, NormalizeNode, LinSpaceNode, RepeatNode,
  ShuffleNode, NthElementNode, InterleaveNode, PadNode, GeometricNode,
  FibonacciNode, StandardizeNode, CovarianceNode, FisherNode, BitwiseNode,
  InterestRateNode, DepreciationNode,
  TvmNode, RateNode, IpmtPpmtNode, NpvNode, IrrNode, MirrNode, CumPmtNode,
  NormDistNode, NormInvNode, NormSDistNode, NormSInvNode,
  TDistNode, TInvNode, ChisqDistNode, ChisqInvNode,
  FDistNode, FInvNode, BetaDistNode, BetaInvNode,
  GammaDistNode, GammaInvNode, LognormDistNode, LognormInvNode,
  WeibullDistNode, ExponDistNode,
  BinomDistNode, BinomInvNode, PoissonDistNode, HypgeomDistNode, NegbinomDistNode,
  RegressionNode, ForecastNode, ModeNode, TrimMeanNode, FrequencyNode, ConfidenceNode,
  SeriesSumNode, MultinomialNode, RollingNode, SwitchNode, IfsNode,
  ZTestNode, TTestNode, FTestNode, ChisqTestNode,
  TrendNode, LinestNode, LogestNode, BinomDistRangeNode, ModMultNode,
  FvScheduleNode, IspmtNode, DollarNode, VdbNode, ProbNode,
  PdurationNode, RriNode, WeightedNode, BaseConvertNode,
  TextInputNode, TextTransformNode, TextLenNode, ConcatNode, TextSliceNode,
  TextFindNode, SubstituteNode, TextReplaceNode,
  ReptNode, ExactNode,
  CharCodeNode, TextJoinNode, TextSplitNode, TextAfterBeforeNode,
  TextFilterNode, NumberValueNode, RomanArabicNode, FixedNode, TextMapNode, UrlEncodeNode,
  TodayNowNode, DateConstructNode, TimeConstructNode,
  DateValueNode, TimeValueNode, DatePartNode, WeekInfoNode,
  DateDiffNode, DateAddNode, WorkdayNode, NetworkdaysNode, DateIfNode,
  RandArrayNode, SequenceNode,
  SortByNode, XMatchNode,
  TBillNode, SecurityDiscNode, CouponNode, AccrintNode,
  AccrintMNode, PriceDiscNode, PriceMatNode, DurationNode, XnpvNode,
  BondPriceNode, XirrNode, OddCouponNode,
  ComplexFromNode, ComplexUnpackNode, ComplexUnaryNode, ComplexBinaryNode, ComplexPowerNode,
  TableInputNode, MatDetNode, TableMultNode, TableUnitNode, TableTransposeNode,
  HStackTableNode, TableReshapeNode, TableSelectNode, TableInfoNode,
  MapTableNode, ByAxisNode, MakeArrayNode, ReduceLambdaNode, LambdaNode,
  FrameInputNode, BuildFrameNode, SplitFrameNode, GetColumnNode, AddColumnNode, GetRowNode, DistinctNode,
  HeadNode, SortFrameNode, FilterFrameNode, JoinNode,
  SelectColumnsNode, DropColumnsNode, GroupByFrameNode, PivotNode, UnpivotNode, NestNode, UnnestNode, AppendNode, RenameNode,
  SplitColumnNode, AddIndexNode, DecisionMatrixNode, DecisionSensitivityNode,
  ReconcileNode,
  BuildCubeNode, NestJoinNode, CubeColumnsNode, CubeRollupNode,
  WebSourceNode, CsvConnectionNode, ParquetConnectionNode, ImportHtmlNode, ImportXmlNode, DataFeedNode,
  WriteCsvNode, WriteJsonNode,
  GroupNode,
  CompositeNode, CompositeInputNode, CompositeOutputNode,
  IsEvenOddNode, FormatDollarNode,
  FormatControllerNode,
  ExpressionNode,
  RegexNode,
  GroupByNode,
  HypotenuseNode,
  ParallelCombineNode, ESeriesNode, AwgNode,
  PhysicsConstantNode,
  ColebrookNode,
  IsaAtmosphereNode, AntoineNode,
  IsInNode, TallyNode,
  ReverseTextNode, SpellNumberNode,
  SolarPositionNode, SunriseSunsetNode, MoonPhaseNode,
  ElementNode, MolarMassNode,
  PromoNode,
  PlaceholderNode,
  ExpectNode,
  TornadoNode,
} from "./rete-nodes";
import {
  AngleDialComponent, SlicerComponent, CableSwitchComponent, NoteComponent, ReportComponent, SessionHistoryComponent, PresentationComponent, ImageComponent,
  SparklineComponent, ChartComponent, HistogramComponent, KpiComponent, BulletComponent, TreemapComponent, SankeyComponent, MermaidComponent, GaugeComponent, HeatmapCellComponent, ChartBuilderComponent, DatePickerComponent, DateRangeComponent, XYPadComponent,
  NumberInputComponent, ArithmeticComponent, DisplayComponent, ComparisonComponent,
  MathFnComponent, ClampComponent, BooleanComponent, NotComponent, IfComponent, ConduitComponent, CastComponent,
  ConstantComponent, MRoundComponent, ListInputComponent, AggregateComponent,
  RangeComponent, ListLengthComponent, ListIndexComponent, SortComponent,
  ReverseComponent, SliceComponent, FilterComponent, FillComponent,
  XLookupComponent, GcdComponent, IFErrorComponent, RandBetweenComponent,
  RoundNComponent, ConvertComponent, UniqueComponent, SetOpComponent, SetRelationComponent, TakeComponent, DropComponent,
  VStackComponent, CumulativeComponent, DiffComponent, ArgMinMaxComponent,
  ContainsComponent, NthValueComponent, PercentileComponent, QuartileComponent,
  PercentrankComponent, RankComponent, CorrelComponent, CombinatoricsComponent,
  TwoInputMathComponent, SumProductComponent, ChooseComponent, BooleanInputComponent,
  SliderInputComponent, ColorPickerComponent, IsTestComponent, NaComponent, AlertComponent,
  NormalizeComponent, LinSpaceComponent, RepeatComponent, ShuffleComponent,
  NthElementComponent, InterleaveComponent, PadComponent, GeometricComponent,
  FibonacciComponent, StandardizeComponent, CovarianceComponent, FisherComponent,
  BesselComponent, BitwiseComponent, InterestRateComponent, DepreciationComponent,
  TvmComponent, RateComponent, IpmtPpmtComponent, NpvComponent, IrrComponent,
  MirrComponent, CumPmtComponent,
  NormDistComponent, NormInvComponent, NormSDistComponent, NormSInvComponent,
  TDistComponent, TInvComponent, ChisqDistComponent, ChisqInvComponent,
  FDistComponent, FInvComponent, BetaDistComponent, BetaInvComponent,
  GammaDistComponent, GammaInvComponent, LognormDistComponent, LognormInvComponent,
  WeibullDistComponent, ExponDistComponent,
  BinomDistComponent, BinomInvComponent, PoissonDistComponent,
  HypgeomDistComponent, NegbinomDistComponent,
  RegressionComponent, ForecastComponent, ModeComponent, TrimMeanComponent,
  FrequencyComponent, ConfidenceComponent, SeriesSumComponent, MultinomialComponent,
  RollingComponent, SwitchComponent, IfsComponent,
  ZTestComponent, TTestComponent, FTestComponent, ChisqTestComponent,
  TrendComponent, LinestComponent, LogestComponent, BinomDistRangeComponent, ModMultComponent,
  FvScheduleComponent, IspmtComponent, DollarComponent, VdbComponent, ProbComponent,
  PdurationComponent, RriComponent, WeightedComponent, BaseConvertComponent,
  TextInputComponent, TextTransformComponent, TextLenComponent, ConcatComponent,
  TextSliceComponent, TextFindComponent, SubstituteComponent, TextReplaceComponent,
  ReptComponent, ExactComponent,
  CharCodeComponent, TextJoinComponent, TextSplitComponent, TextAfterBeforeComponent,
  TextFilterComponent, NumberValueComponent, RomanArabicComponent, FixedComponent, TextMapComponent, UrlEncodeComponent,
  TodayNowComponent, DateConstructComponent, TimeConstructComponent,
  DateValueComponent, TimeValueComponent, DatePartComponent,
  WeekInfoComponent, DateDiffComponent, DateAddComponent,
  WorkdayComponent, NetworkdaysComponent, DateIfComponent,
  RandArrayComponent, SequenceComponent,
  SortByComponent, XMatchComponent,
  TBillComponent, SecurityDiscComponent, CouponComponent, AccrintComponent,
  AccrintMComponent, PriceDiscComponent, PriceMatComponent, DurationComponent, XnpvComponent,
  BondPriceComponent, XirrComponent, OddCouponComponent,
  ComplexFromComponent, ComplexUnpackComponent, ComplexUnaryComponent, ComplexBinaryComponent, ComplexPowerComponent,
  TableInputComponent, MatDetComponent, TableMultComponent, TableUnitComponent, TableTransposeComponent,
  HStackTableComponent, TableReshapeComponent, TableSelectComponent, TableInfoComponent,
  MapTableComponent, ByAxisComponent, MakeArrayComponent, ReduceLambdaComponent, LambdaComponent,
  FrameInputComponent, BuildFrameComponent, SplitFrameComponent, GetColumnComponent, AddColumnComponent, GetRowComponent,
  DistinctComponent, HeadComponent, SortFrameComponent, FilterFrameComponent, JoinComponent,
  SelectColumnsComponent, DropColumnsComponent, GroupByFrameComponent, PivotComponent, UnpivotComponent,
  NestComponent, UnnestComponent, AppendComponent, RenameComponent,
  SplitColumnComponent, AddIndexComponent, DecisionMatrixComponent, DecisionSensitivityComponent,
  ReconcileComponent,
  BuildCubeComponent, NestJoinComponent, CubeColumnsComponent, CubeRollupComponent,
  WebSourceComponent, CsvConnectionComponent, ParquetConnectionComponent, ImportHtmlComponent, ImportXmlComponent, DataFeedComponent,
  WriteCsvComponent, WriteJsonComponent,
  GroupComponent,
  CompositeComponent, CompositeInputMarkerComponent, CompositeOutputMarkerComponent,
  FormatDollarComponent, IsEvenOddComponent,
  FormatControllerComponent,
  ExpressionComponent,
  RegexComponent,
  GroupByComponent,
  HypotenuseComponent,
  ParallelCombineComponent, ESeriesComponent, AwgComponent,
  PhysicsConstantComponent,
  ColebrookComponent,
  IsaAtmosphereComponent, AntoineComponent,
  IsInComponent, TallyComponent,
  ReverseTextComponent, SpellNumberComponent,
  SolarPositionComponent, SunriseSunsetComponent, MoonPhaseComponent,
  ElementComponent, MolarMassComponent,
  PromoComponent,
  PlaceholderComponent,
  ExpectComponent,
  TornadoComponent,
} from "./components";

export type AnyNodeComponent = JSXElementConstructor<{
  data: ClassicPreset.Node & { width?: number; height?: number };
  emit: RenderEmit<Schemes>;
}>;

type NodeCtor = abstract new (...args: never[]) => ClassicPreset.Node;

const comp = (c: unknown) => c as unknown as AnyNodeComponent;

export const NODE_COMPONENTS: ReadonlyArray<readonly [NodeCtor, AnyNodeComponent]> = [
  [AngleDialNode,   comp(AngleDialComponent)],
  [SlicerNode,      comp(SlicerComponent)],
  [CableSwitchNode, comp(CableSwitchComponent)],
  [NoteNode,        comp(NoteComponent)],
  [ReportNode,      comp(ReportComponent)],
  [SessionHistoryNode, comp(SessionHistoryComponent)],
  [PresentationNode, comp(PresentationComponent)],
  [ImageNode,       comp(ImageComponent)],
  [SparklineNode,   comp(SparklineComponent)],
  [ChartNode,       comp(ChartComponent)],
  [HistogramNode,   comp(HistogramComponent)],
  [KpiNode,         comp(KpiComponent)],
  [BulletNode,      comp(BulletComponent)],
  [TreemapNode,     comp(TreemapComponent)],
  [SankeyNode,      comp(SankeyComponent)],
  [MermaidNode,     comp(MermaidComponent)],
  [GaugeNode,       comp(GaugeComponent)],
  [HeatmapCellNode, comp(HeatmapCellComponent)],
  [ChartBuilderNode, comp(ChartBuilderComponent)],
  [DatePickerNode,  comp(DatePickerComponent)],
  [DateRangeNode,   comp(DateRangeComponent)],
  [XYPadNode,       comp(XYPadComponent)],
  [NumberInputNode, comp(NumberInputComponent)],
  [ArithmeticNode,  comp(ArithmeticComponent)],
  [DisplayNode,     comp(DisplayComponent)],
  [ComparisonNode,  comp(ComparisonComponent)],
  [MathFnNode,      comp(MathFnComponent)],
  [ClampNode,       comp(ClampComponent)],
  [BooleanOpNode,   comp(BooleanComponent)],
  [NotNode,         comp(NotComponent)],
  [IfNode,          comp(IfComponent)],
  [ConduitNode,      comp(ConduitComponent)],
  [CastNode,        comp(CastComponent)],
  [ConstantNode,    comp(ConstantComponent)],
  [MRoundNode,      comp(MRoundComponent)],
  [ListInputNode, comp(ListInputComponent)],
  [AggregateNode,   comp(AggregateComponent)],
  [RangeNode,       comp(RangeComponent)],
  [ListLengthNode,  comp(ListLengthComponent)],
  [ListIndexNode,   comp(ListIndexComponent)],
  [SortNode,        comp(SortComponent)],
  [ReverseNode,     comp(ReverseComponent)],
  [SliceNode,       comp(SliceComponent)],
  [FilterNode,      comp(FilterComponent)],
  [FillNode,        comp(FillComponent)],
  [XLookupNode,     comp(XLookupComponent)],
  [GcdNode,         comp(GcdComponent)],
  [IFErrorNode,     comp(IFErrorComponent)],
  [RandBetweenNode, comp(RandBetweenComponent)],
  [RoundNNode,      comp(RoundNComponent)],
  [ConvertNode,     comp(ConvertComponent)],
  [UniqueNode,      comp(UniqueComponent)],
  [SetOpNode,       comp(SetOpComponent)],
  [SetRelationNode, comp(SetRelationComponent)],
  [TakeNode,        comp(TakeComponent)],
  [DropNode,        comp(DropComponent)],
  [VStackNode,      comp(VStackComponent)],
  [CumulativeNode,  comp(CumulativeComponent)],
  [DiffNode,        comp(DiffComponent)],
  [ArgMinMaxNode,   comp(ArgMinMaxComponent)],
  [ContainsNode,    comp(ContainsComponent)],
  [NthValueNode,    comp(NthValueComponent)],
  [PercentileNode,  comp(PercentileComponent)],
  [QuartileNode,    comp(QuartileComponent)],
  [PercentrankNode, comp(PercentrankComponent)],
  [RankNode,        comp(RankComponent)],
  [CorrelNode,      comp(CorrelComponent)],
  [BesselNode,        comp(BesselComponent)],
  [CombinatoricsNode, comp(CombinatoricsComponent)],
  [TwoInputMathNode,  comp(TwoInputMathComponent)],
  [SumProductNode,    comp(SumProductComponent)],
  [ChooseNode,        comp(ChooseComponent)],
  [BooleanInputNode,  comp(BooleanInputComponent)],
  [SliderInputNode,   comp(SliderInputComponent)],
  [ColorPickerNode,   comp(ColorPickerComponent)],
  [IsTestNode,      comp(IsTestComponent)],
  [NaNode,          comp(NaComponent)],
  [AlertNode,       comp(AlertComponent)],
  [NormalizeNode,   comp(NormalizeComponent)],
  [LinSpaceNode,    comp(LinSpaceComponent)],
  [RepeatNode,      comp(RepeatComponent)],
  [ShuffleNode,     comp(ShuffleComponent)],
  [NthElementNode,  comp(NthElementComponent)],
  [InterleaveNode,  comp(InterleaveComponent)],
  [PadNode,         comp(PadComponent)],
  [GeometricNode,   comp(GeometricComponent)],
  [FibonacciNode,   comp(FibonacciComponent)],
  [StandardizeNode, comp(StandardizeComponent)],
  [CovarianceNode,  comp(CovarianceComponent)],
  [FisherNode,      comp(FisherComponent)],
  [BitwiseNode,     comp(BitwiseComponent)],
  [InterestRateNode, comp(InterestRateComponent)],
  [DepreciationNode, comp(DepreciationComponent)],
  [TvmNode,          comp(TvmComponent)],
  [RateNode,         comp(RateComponent)],
  [IpmtPpmtNode,     comp(IpmtPpmtComponent)],
  [NpvNode,          comp(NpvComponent)],
  [IrrNode,          comp(IrrComponent)],
  [MirrNode,         comp(MirrComponent)],
  [CumPmtNode,       comp(CumPmtComponent)],
  [NormDistNode,     comp(NormDistComponent)],
  [NormInvNode,      comp(NormInvComponent)],
  [NormSDistNode,    comp(NormSDistComponent)],
  [NormSInvNode,     comp(NormSInvComponent)],
  [TDistNode,        comp(TDistComponent)],
  [TInvNode,         comp(TInvComponent)],
  [ChisqDistNode,    comp(ChisqDistComponent)],
  [ChisqInvNode,     comp(ChisqInvComponent)],
  [FDistNode,        comp(FDistComponent)],
  [FInvNode,         comp(FInvComponent)],
  [BetaDistNode,     comp(BetaDistComponent)],
  [BetaInvNode,      comp(BetaInvComponent)],
  [GammaDistNode,    comp(GammaDistComponent)],
  [GammaInvNode,     comp(GammaInvComponent)],
  [LognormDistNode,  comp(LognormDistComponent)],
  [LognormInvNode,   comp(LognormInvComponent)],
  [WeibullDistNode,  comp(WeibullDistComponent)],
  [ExponDistNode,    comp(ExponDistComponent)],
  [BinomDistNode,    comp(BinomDistComponent)],
  [BinomInvNode,     comp(BinomInvComponent)],
  [PoissonDistNode,  comp(PoissonDistComponent)],
  [HypgeomDistNode,  comp(HypgeomDistComponent)],
  [NegbinomDistNode, comp(NegbinomDistComponent)],
  [RegressionNode,   comp(RegressionComponent)],
  [ForecastNode,     comp(ForecastComponent)],
  [ModeNode,         comp(ModeComponent)],
  [TrimMeanNode,     comp(TrimMeanComponent)],
  [FrequencyNode,    comp(FrequencyComponent)],
  [ConfidenceNode,   comp(ConfidenceComponent)],
  [SeriesSumNode,    comp(SeriesSumComponent)],
  [MultinomialNode,  comp(MultinomialComponent)],
  [RollingNode,      comp(RollingComponent)],
  [SwitchNode,       comp(SwitchComponent)],
  [IfsNode,          comp(IfsComponent)],
  [ZTestNode,        comp(ZTestComponent)],
  [TTestNode,        comp(TTestComponent)],
  [FTestNode,        comp(FTestComponent)],
  [ChisqTestNode,    comp(ChisqTestComponent)],
  [TrendNode,        comp(TrendComponent)],
  [LinestNode,       comp(LinestComponent)],
  [LogestNode,       comp(LogestComponent)],
  [BinomDistRangeNode, comp(BinomDistRangeComponent)],
  [ModMultNode,      comp(ModMultComponent)],
  [FvScheduleNode,   comp(FvScheduleComponent)],
  [IspmtNode,        comp(IspmtComponent)],
  [DollarNode,       comp(DollarComponent)],
  [VdbNode,          comp(VdbComponent)],
  [ProbNode,         comp(ProbComponent)],
  [PdurationNode,    comp(PdurationComponent)],
  [RriNode,          comp(RriComponent)],
  [WeightedNode,     comp(WeightedComponent)],
  [BaseConvertNode,  comp(BaseConvertComponent)],
  [TextInputNode,  comp(TextInputComponent)],
  [TextTransformNode,comp(TextTransformComponent)],
  [TextLenNode,      comp(TextLenComponent)],
  [ConcatNode,       comp(ConcatComponent)],
  [TextSliceNode,    comp(TextSliceComponent)],
  [TextFindNode,     comp(TextFindComponent)],
  [SubstituteNode,   comp(SubstituteComponent)],
  [TextReplaceNode,  comp(TextReplaceComponent)],
  [ReptNode,              comp(ReptComponent)],
  [ExactNode,             comp(ExactComponent)],
  [CharCodeNode,          comp(CharCodeComponent)],
  [TextJoinNode,          comp(TextJoinComponent)],
  [TextSplitNode,         comp(TextSplitComponent)],
  [TextAfterBeforeNode,   comp(TextAfterBeforeComponent)],
  [NumberValueNode,       comp(NumberValueComponent)],
  [RomanArabicNode,       comp(RomanArabicComponent)],
  [FixedNode,             comp(FixedComponent)],
  [TextMapNode,           comp(TextMapComponent)],
  [UrlEncodeNode,         comp(UrlEncodeComponent)],
  [TodayNowNode,          comp(TodayNowComponent)],
  [DateConstructNode,     comp(DateConstructComponent)],
  [TimeConstructNode,     comp(TimeConstructComponent)],
  [DateValueNode,         comp(DateValueComponent)],
  [TimeValueNode,         comp(TimeValueComponent)],
  [DatePartNode,          comp(DatePartComponent)],
  [WeekInfoNode,          comp(WeekInfoComponent)],
  [DateDiffNode,          comp(DateDiffComponent)],
  [DateAddNode,           comp(DateAddComponent)],
  [WorkdayNode,           comp(WorkdayComponent)],
  [NetworkdaysNode,       comp(NetworkdaysComponent)],
  [DateIfNode,            comp(DateIfComponent)],
  [RandArrayNode,         comp(RandArrayComponent)],
  [SequenceNode,          comp(SequenceComponent)],
  [SortByNode,            comp(SortByComponent)],
  [XMatchNode,            comp(XMatchComponent)],
  [TBillNode,             comp(TBillComponent)],
  [SecurityDiscNode,      comp(SecurityDiscComponent)],
  [CouponNode,            comp(CouponComponent)],
  [AccrintNode,           comp(AccrintComponent)],
  [AccrintMNode,          comp(AccrintMComponent)],
  [PriceDiscNode,         comp(PriceDiscComponent)],
  [PriceMatNode,          comp(PriceMatComponent)],
  [DurationNode,          comp(DurationComponent)],
  [XnpvNode,              comp(XnpvComponent)],
  [BondPriceNode,         comp(BondPriceComponent)],
  [XirrNode,              comp(XirrComponent)],
  [OddCouponNode,         comp(OddCouponComponent)],
  [IsEvenOddNode,         comp(IsEvenOddComponent)],
  [FormatDollarNode,      comp(FormatDollarComponent)],
  [TableInputNode,        comp(TableInputComponent)],
  [MatDetNode,            comp(MatDetComponent)],
  [TableMultNode,         comp(TableMultComponent)],
  [TableUnitNode,         comp(TableUnitComponent)],
  [TableTransposeNode,    comp(TableTransposeComponent)],
  [HStackTableNode,       comp(HStackTableComponent)],
  [TableReshapeNode,      comp(TableReshapeComponent)],
  [TableSelectNode,       comp(TableSelectComponent)],
  [TableInfoNode,         comp(TableInfoComponent)],
  [MapTableNode,          comp(MapTableComponent)],
  [ByAxisNode,            comp(ByAxisComponent)],
  [MakeArrayNode,         comp(MakeArrayComponent)],
  [ReduceLambdaNode,      comp(ReduceLambdaComponent)],
  [LambdaNode,            comp(LambdaComponent)],
  [FrameInputNode,        comp(FrameInputComponent)],
  [WebSourceNode,         comp(WebSourceComponent)],
  [DataFeedNode,          comp(DataFeedComponent)],
  [CsvConnectionNode,     comp(CsvConnectionComponent)],
  [ParquetConnectionNode, comp(ParquetConnectionComponent)],
  [ImportHtmlNode,        comp(ImportHtmlComponent)],
  [ImportXmlNode,         comp(ImportXmlComponent)],
  [WriteCsvNode,          comp(WriteCsvComponent)],
  [WriteJsonNode,         comp(WriteJsonComponent)],
  [BuildFrameNode,        comp(BuildFrameComponent)],
  [SplitFrameNode,        comp(SplitFrameComponent)],
  [GetColumnNode,         comp(GetColumnComponent)],
  [AddColumnNode,         comp(AddColumnComponent)],
  [GetRowNode,            comp(GetRowComponent)],
  [DistinctNode,          comp(DistinctComponent)],
  [HeadNode,              comp(HeadComponent)],
  [SortFrameNode,         comp(SortFrameComponent)],
  [FilterFrameNode,       comp(FilterFrameComponent)],
  [JoinNode,              comp(JoinComponent)],
  [SelectColumnsNode,     comp(SelectColumnsComponent)],
  [DropColumnsNode,       comp(DropColumnsComponent)],
  [GroupByFrameNode,      comp(GroupByFrameComponent)],
  [PivotNode,             comp(PivotComponent)],
  [UnpivotNode,           comp(UnpivotComponent)],
  [NestNode,              comp(NestComponent)],
  [UnnestNode,            comp(UnnestComponent)],
  [AppendNode,            comp(AppendComponent)],
  [RenameNode,            comp(RenameComponent)],
  [SplitColumnNode,       comp(SplitColumnComponent)],
  [AddIndexNode,          comp(AddIndexComponent)],
  [DecisionMatrixNode,    comp(DecisionMatrixComponent)],
  [DecisionSensitivityNode, comp(DecisionSensitivityComponent)],
  [ReconcileNode,         comp(ReconcileComponent)],
  [BuildCubeNode,         comp(BuildCubeComponent)],
  [NestJoinNode,          comp(NestJoinComponent)],
  [CubeColumnsNode,       comp(CubeColumnsComponent)],
  [CubeRollupNode,        comp(CubeRollupComponent)],
  [GroupNode,             comp(GroupComponent)],
  [CompositeNode,         comp(CompositeComponent)],
  // Boundary markers — rendered only inside the Composite drill-in editor's
  // own rete root (they never live on the main canvas).
  [CompositeInputNode,    comp(CompositeInputMarkerComponent)],
  [CompositeOutputNode,   comp(CompositeOutputMarkerComponent)],
  [ComplexFromNode,       comp(ComplexFromComponent)],
  [ComplexUnpackNode,     comp(ComplexUnpackComponent)],
  [ComplexUnaryNode,      comp(ComplexUnaryComponent)],
  [ComplexBinaryNode,     comp(ComplexBinaryComponent)],
  [ComplexPowerNode,      comp(ComplexPowerComponent)],
  [TextFilterNode,        comp(TextFilterComponent)],
  [FormatControllerNode,  comp(FormatControllerComponent)],
  [ExpressionNode,        comp(ExpressionComponent)],
  [RegexNode,             comp(RegexComponent)],
  [GroupByNode,           comp(GroupByComponent)],
  // Packs (example built-in pack node — registered always so saved graphs that
  // use it still render even when the pack is deactivated).
  [HypotenuseNode,        comp(HypotenuseComponent)],
  [ParallelCombineNode,   comp(ParallelCombineComponent)],
  [ESeriesNode,           comp(ESeriesComponent)],
  [AwgNode,               comp(AwgComponent)],
  [PhysicsConstantNode,   comp(PhysicsConstantComponent)],
  [ColebrookNode,         comp(ColebrookComponent)],
  [IsaAtmosphereNode,     comp(IsaAtmosphereComponent)],
  [AntoineNode,           comp(AntoineComponent)],
  [IsInNode,              comp(IsInComponent)],
  [TallyNode,             comp(TallyComponent)],
  [ReverseTextNode,       comp(ReverseTextComponent)],
  [SpellNumberNode,       comp(SpellNumberComponent)],
  [SolarPositionNode,     comp(SolarPositionComponent)],
  [SunriseSunsetNode,     comp(SunriseSunsetComponent)],
  [MoonPhaseNode,         comp(MoonPhaseComponent)],
  [ElementNode,           comp(ElementComponent)],
  [MolarMassNode,         comp(MolarMassComponent)],
  [PromoNode,             comp(PromoComponent)],
  // Load-time stand-in for an unregistered saved type (pack off / renamed).
  [PlaceholderNode,       comp(PlaceholderComponent)],
  [ExpectNode,            comp(ExpectComponent)],
  [TornadoNode,           comp(TornadoComponent)],
];
