// Maps every node class to its React component — one row per node.

import { ClassicPreset } from "rete";
import type { JSXElementConstructor } from "react";
import type { RenderEmit } from "rete-react-plugin";
import type { Schemes } from "./schemes";
import {
  AngleDialNode, SlicerNode, CableSwitchNode, NoteNode, ReportNode, SessionHistoryNode, PresentationNode, ImageNode, SvgPickerNode,
  SparklineNode, ChartNode, HistogramNode, KpiNode, BulletNode, TreemapNode, SankeyNode, SurfaceNode, MermaidNode, GaugeNode, HeatmapCellNode, ChartBuilderNode, DatePickerNode, DateRangeNode, XYPadNode,
  WaterfallNode, CandlestickNode, BoxplotNode, CalendarHeatmapNode, WaffleNode, QuiverNode, SevenSegNode,
  PointPlotterNode, CurveNode, GridPainterNode,
  FillBlanksNode, ReplaceValuesNode, MergeColumnsNode, HeadersNode, DropBlankRowsNode,
  NumberInputNode, ArithmeticNode, DisplayNode, ComparisonNode, MathFnNode,
  ColorPickerNode,
  ColorBlendNode,
  ClampNode, BooleanOpNode, NotNode, IfNode, ConduitNode, CastNode, ConstantNode, MRoundNode,
  ListInputNode, AggregateNode, SeriesNode, ListLengthNode, ListIndexNode,
  SortNode, ReverseNode, SliceNode, FilterNode, SumIfsNode, FillNode, XLookupNode,
  GcdNode, IFErrorNode, RandBetweenNode, RoundNNode, ConvertNode,
  UniqueNode, SetOpNode, SetRelationNode, ListTakeDropNode, VStackNode, ConcatListsNode, FrameFromListsNode, QuadraticRootsNode, RunningNode, DiffNode,
  ArgMinMaxNode, ContainsNode, RankPercentileNode,
  CorrelNode, BesselNode, CombinatoricsNode, TwoInputMathNode,
  SumProductNode, ChooseNode, BooleanInputNode, SliderInputNode, IsTestNode,
  NaNode, AlertNode, NormalizeNode, RepeatNode,
  ShuffleNode, NthElementNode, InterleaveNode, PadNode, GeometricNode,
  FibonacciNode, StandardizeNode, CovarianceNode, FisherNode, BitwiseNode,
  DepreciationNode,
  TvmNode, IpmtPpmtNode, NpvNode, IrrNode, MirrNode, CumPmtNode,
  DistributionNode,
  RegressionNode, ForecastNode, ModeNode, TrimMeanNode, FrequencyNode, ConfidenceNode,
  SeriesSumNode, MultinomialNode, SwitchNode, IfsNode,
  HypothesisTestNode,
  TrendNode, InterpolateNode, LinestNode, LogestNode, BinomDistRangeNode,
  FvScheduleNode, IspmtNode, DollarNode, ProbNode,
  WeightedNode, BaseConvertNode,
  TextInputNode, TextTransformNode, TextLenNode, ConcatNode, TextSliceNode,
  TextFindNode, SubstituteNode, TextReplaceNode,
  ReptNode, ExactNode,
  CharCodeNode, TextJoinNode, TextSplitNode, TextAfterBeforeNode,
  TextFilterNode, NumberValueNode, RomanArabicNode, FixedNode, UrlEncodeNode,
  TodayNowNode, DateConstructNode, TimeConstructNode,
  DateValueNode, TimeValueNode, DatePartNode, WeekInfoNode,
  DateDiffNode, DateAddNode, WorkdaysNode,
  RandArrayNode,
  SortByNode, XMatchNode,
  TBillNode, SecurityDiscNode, CouponNode, AccrintNode,
  AccrintMNode, PriceDiscNode, PriceMatNode, DurationNode,
  BondPriceNode, OddCouponNode,
  ComplexFromNode, ComplexUnpackNode, ComplexUnaryNode, ComplexBinaryNode, ComplexPowerNode,
  TableInputNode, MatDetNode, TableMultNode, TableUnitNode, TableTransposeNode,
  HStackTableNode, TableReshapeNode, TableSelectNode, TableTakeDropNode, ExpandNode, TableInfoNode,
  MapTableNode, ByAxisNode, MakeArrayNode, ReduceLambdaNode, ScanLambdaNode, LambdaNode,
  FrameInputNode, BuildFrameNode, SplitFrameNode, GetColumnNode, AddColumnNode, ComputedColumnNode, GetRowNode, DistinctNode,
  HeadNode, SortFrameNode, FilterFrameNode, JoinNode,
  SelectColumnsNode, DropColumnsNode, GroupByFrameNode, PivotNode, UnpivotNode, NestNode, UnnestNode, AppendNode, RenameNode,
  SplitColumnNode, AddIndexNode, DecisionMatrixNode, DecisionSensitivityNode,
  ReconcileNode,
  BuildCubeNode, NestJoinNode, CubeColumnsNode, CubeRollupNode,
  WebSourceNode, CsvConnectionNode, ParquetConnectionNode, ImportHtmlNode, ImportXmlNode, DataFeedNode,
  WriteCsvNode, WriteJsonNode, WriteObsidianNode, ImportObsidianNode,
  GroupNode,
  CompositeNode, CompositeInputNode, CompositeOutputNode,
  IsEvenOddNode, FormatDollarNode,
  FormatControllerNode,
  ExpressionNode,
  EquationNode,
  RegexNode,
  GroupByNode,
  HypotenuseNode,
  ParallelCombineNode, ESeriesNode, AwgNode,
  PhysicsConstantNode,
  ColebrookNode,
  IsaAtmosphereNode, AntoineNode,
  IsInNode, TallyNode,
  ReverseTextNode, SpellNumberNode,
  SolarPositionNode, SunriseSunsetNode, MoonPhaseNode,
  ElementNode, MolarMassNode, ResistorCodeNode, EmSpectrumNode, HrZonesNode, PipeRoughnessNode, TriangleSolverNode,
  PromoNode,
  PlaceholderNode,
  ExpectNode,
  TornadoNode,
} from "./rete-nodes";
import {
  AngleDialComponent, SlicerComponent, CableSwitchComponent, NoteComponent, ReportComponent, SessionHistoryComponent, PresentationComponent, ImageComponent, SvgPickerComponent,
  SparklineComponent, ChartComponent, HistogramComponent, KpiComponent, BulletComponent, TreemapComponent, SankeyComponent, SurfaceComponent, MermaidComponent, GaugeComponent, HeatmapCellComponent, ChartBuilderComponent, DatePickerComponent, DateRangeComponent, XYPadComponent,
  WaterfallComponent, CandlestickComponent, BoxplotComponent, CalendarHeatmapComponent, WaffleComponent, QuiverComponent, SevenSegComponent,
  PointPlotterComponent, CurveComponent, GridPainterComponent,
  FillBlanksComponent, ReplaceValuesComponent, MergeColumnsComponent, HeadersComponent, DropBlankRowsComponent,
  NumberInputComponent, ArithmeticComponent, DisplayComponent, ComparisonComponent,
  MathFnComponent, ClampComponent, BooleanComponent, NotComponent, IfComponent, ConduitComponent, CastComponent,
  ConstantComponent, MRoundComponent, ListInputComponent, AggregateComponent,
  SeriesComponent, ListLengthComponent, ListIndexComponent, SortComponent,
  ReverseComponent, SliceComponent, FilterComponent, SumIfsComponent, FillComponent,
  XLookupComponent, GcdComponent, IFErrorComponent, RandBetweenComponent,
  RoundNComponent, ConvertComponent, UniqueComponent, SetOpComponent, SetRelationComponent, ListTakeDropComponent,
  VStackComponent, ConcatListsComponent, FrameFromListsComponent, QuadraticRootsComponent, RunningComponent, DiffComponent, ArgMinMaxComponent,
  ContainsComponent, RankPercentileComponent, CorrelComponent, CombinatoricsComponent,
  TwoInputMathComponent, SumProductComponent, ChooseComponent, BooleanInputComponent,
  SliderInputComponent, ColorPickerComponent, ColorBlendComponent, IsTestComponent, NaComponent, AlertComponent,
  NormalizeComponent, RepeatComponent, ShuffleComponent,
  NthElementComponent, InterleaveComponent, PadComponent, GeometricComponent,
  FibonacciComponent, StandardizeComponent, CovarianceComponent, FisherComponent,
  BesselComponent, BitwiseComponent, DepreciationComponent,
  TvmComponent, IpmtPpmtComponent, NpvComponent, IrrComponent,
  MirrComponent, CumPmtComponent,
  DistributionComponent,
  RegressionComponent, ForecastComponent, ModeComponent, TrimMeanComponent,
  FrequencyComponent, ConfidenceComponent, SeriesSumComponent, MultinomialComponent,
  SwitchComponent, IfsComponent,
  HypothesisTestComponent,
  TrendComponent, InterpolateComponent, LinestComponent, LogestComponent, BinomDistRangeComponent,
  FvScheduleComponent, IspmtComponent, DollarComponent, ProbComponent,
  WeightedComponent, BaseConvertComponent,
  TextInputComponent, TextTransformComponent, TextLenComponent, ConcatComponent,
  TextSliceComponent, TextFindComponent, SubstituteComponent, TextReplaceComponent,
  ReptComponent, ExactComponent,
  CharCodeComponent, TextJoinComponent, TextSplitComponent, TextAfterBeforeComponent,
  TextFilterComponent, NumberValueComponent, RomanArabicComponent, FixedComponent, UrlEncodeComponent,
  TodayNowComponent, DateConstructComponent, TimeConstructComponent,
  DateValueComponent, TimeValueComponent, DatePartComponent,
  WeekInfoComponent, DateDiffComponent, DateAddComponent,
  WorkdaysComponent,
  RandArrayComponent,
  SortByComponent, XMatchComponent,
  TBillComponent, SecurityDiscComponent, CouponComponent, AccrintComponent,
  AccrintMComponent, PriceDiscComponent, PriceMatComponent, DurationComponent,
  BondPriceComponent, OddCouponComponent,
  ComplexFromComponent, ComplexUnpackComponent, ComplexUnaryComponent, ComplexBinaryComponent, ComplexPowerComponent,
  TableInputComponent, MatDetComponent, TableMultComponent, TableUnitComponent, TableTransposeComponent,
  HStackTableComponent, TableReshapeComponent, TableSelectComponent, TableTakeDropComponent, ExpandTableComponent, TableInfoComponent,
  MapTableComponent, ByAxisComponent, MakeArrayComponent, ReduceLambdaComponent, ScanLambdaComponent, LambdaComponent,
  FrameInputComponent, BuildFrameComponent, SplitFrameComponent, GetColumnComponent, AddColumnComponent, ComputedColumnComponent, GetRowComponent,
  DistinctComponent, HeadComponent, SortFrameComponent, FilterFrameComponent, JoinComponent,
  SelectColumnsComponent, DropColumnsComponent, GroupByFrameComponent, PivotComponent, UnpivotComponent,
  NestComponent, UnnestComponent, AppendComponent, RenameComponent,
  SplitColumnComponent, AddIndexComponent, DecisionMatrixComponent, DecisionSensitivityComponent,
  ReconcileComponent,
  BuildCubeComponent, NestJoinComponent, CubeColumnsComponent, CubeRollupComponent,
  WebSourceComponent, CsvConnectionComponent, ParquetConnectionComponent, ImportHtmlComponent, ImportXmlComponent, DataFeedComponent,
  WriteCsvComponent, WriteJsonComponent, WriteObsidianComponent, ImportObsidianComponent,
  GroupComponent,
  CompositeComponent, CompositeInputMarkerComponent, CompositeOutputMarkerComponent,
  FormatDollarComponent, IsEvenOddComponent,
  FormatControllerComponent,
  ExpressionComponent,
  EquationComponent,
  RegexComponent,
  GroupByComponent,
  HypotenuseComponent,
  ParallelCombineComponent, ESeriesComponent, AwgComponent,
  PhysicsConstantComponent,
  ColebrookComponent,
  IsaAtmosphereComponent, AntoineComponent,
  IsInComponent, TallyComponent,
  ReverseTextComponent, SpellNumberComponent,
  SolarPositionComponent, SunriseSunsetComponent, MoonPhaseComponent,
  ElementComponent, MolarMassComponent, ResistorCodeComponent,
  PromoComponent,
  PlaceholderComponent,
  ExpectComponent,
  TornadoComponent,
} from "./components";
import { EmSpectrumComponent, HrZonesComponent, PipeRoughnessComponent, TriangleSolverComponent } from "./components/PackToolNodes";

export type AnyNodeComponent = JSXElementConstructor<{
  data: ClassicPreset.Node & { width?: number; height?: number };
  emit: RenderEmit<Schemes>;
}>;

type NodeCtor = abstract new (...args: never[]) => ClassicPreset.Node;

const comp = (c: unknown) => c as unknown as AnyNodeComponent;

export const NODE_COMPONENTS: ReadonlyArray<readonly [NodeCtor, AnyNodeComponent]> = [
  [AngleDialNode,   comp(AngleDialComponent)],
  [SlicerNode,      comp(SlicerComponent)],
  [CableSwitchNode, comp(CableSwitchComponent)],
  [ImportObsidianNode, comp(ImportObsidianComponent)],
  [NoteNode,        comp(NoteComponent)],
  [ReportNode,      comp(ReportComponent)],
  [SessionHistoryNode, comp(SessionHistoryComponent)],
  [PresentationNode, comp(PresentationComponent)],
  [ImageNode,       comp(ImageComponent)],
  [SvgPickerNode,   comp(SvgPickerComponent)],
  [SparklineNode,   comp(SparklineComponent)],
  [ChartNode,       comp(ChartComponent)],
  [HistogramNode,   comp(HistogramComponent)],
  [KpiNode,         comp(KpiComponent)],
  [BulletNode,      comp(BulletComponent)],
  [TreemapNode,     comp(TreemapComponent)],
  [SankeyNode,      comp(SankeyComponent)],
  [SurfaceNode,     comp(SurfaceComponent)],
  [WaterfallNode,   comp(WaterfallComponent)],
  [CandlestickNode, comp(CandlestickComponent)],
  [BoxplotNode,     comp(BoxplotComponent)],
  [CalendarHeatmapNode, comp(CalendarHeatmapComponent)],
  [WaffleNode,      comp(WaffleComponent)],
  [QuiverNode,      comp(QuiverComponent)],
  [SevenSegNode,    comp(SevenSegComponent)],
  [PointPlotterNode, comp(PointPlotterComponent)],
  [CurveNode,       comp(CurveComponent)],
  [GridPainterNode, comp(GridPainterComponent)],
  [FillBlanksNode,   comp(FillBlanksComponent)],
  [ReplaceValuesNode, comp(ReplaceValuesComponent)],
  [MergeColumnsNode, comp(MergeColumnsComponent)],
  [HeadersNode, comp(HeadersComponent)],
  [DropBlankRowsNode, comp(DropBlankRowsComponent)],
  [MermaidNode,     comp(MermaidComponent)],
  [GaugeNode,       comp(GaugeComponent)],
  [HeatmapCellNode, comp(HeatmapCellComponent)],
  [ChartBuilderNode, comp(ChartBuilderComponent)],
  [DatePickerNode,  comp(DatePickerComponent)],
  [DateRangeNode,   comp(DateRangeComponent)],
  [XYPadNode,       comp(XYPadComponent)],
  [NumberInputNode, comp(NumberInputComponent)],
  [ArithmeticNode,  comp(ArithmeticComponent)],
  [DisplayNode,     comp(DisplayComponent)],
  [ComparisonNode,  comp(ComparisonComponent)],
  [MathFnNode,      comp(MathFnComponent)],
  [ClampNode,       comp(ClampComponent)],
  [BooleanOpNode,   comp(BooleanComponent)],
  [NotNode,         comp(NotComponent)],
  [IfNode,          comp(IfComponent)],
  [ConduitNode,      comp(ConduitComponent)],
  [CastNode,        comp(CastComponent)],
  [ConstantNode,    comp(ConstantComponent)],
  [MRoundNode,      comp(MRoundComponent)],
  [ListInputNode, comp(ListInputComponent)],
  [AggregateNode,   comp(AggregateComponent)],
  [SeriesNode,      comp(SeriesComponent)],
  [ListLengthNode,  comp(ListLengthComponent)],
  [ListIndexNode,   comp(ListIndexComponent)],
  [SortNode,        comp(SortComponent)],
  [ReverseNode,     comp(ReverseComponent)],
  [SliceNode,       comp(SliceComponent)],
  [SumIfsNode,       comp(SumIfsComponent)],
  [FilterNode,      comp(FilterComponent)],
  [FillNode,        comp(FillComponent)],
  [XLookupNode,     comp(XLookupComponent)],
  [GcdNode,         comp(GcdComponent)],
  [IFErrorNode,     comp(IFErrorComponent)],
  [RandBetweenNode, comp(RandBetweenComponent)],
  [RoundNNode,      comp(RoundNComponent)],
  [ConvertNode,     comp(ConvertComponent)],
  [UniqueNode,      comp(UniqueComponent)],
  [SetOpNode,       comp(SetOpComponent)],
  [SetRelationNode, comp(SetRelationComponent)],
  [ListTakeDropNode, comp(ListTakeDropComponent)],
  [VStackNode,      comp(VStackComponent)],
  [ConcatListsNode, comp(ConcatListsComponent)],
  [FrameFromListsNode, comp(FrameFromListsComponent)],
  [QuadraticRootsNode, comp(QuadraticRootsComponent)],
  [RunningNode,     comp(RunningComponent)],
  [DiffNode,        comp(DiffComponent)],
  [ArgMinMaxNode,   comp(ArgMinMaxComponent)],
  [ContainsNode,    comp(ContainsComponent)],
  [RankPercentileNode, comp(RankPercentileComponent)],
  [CorrelNode,      comp(CorrelComponent)],
  [BesselNode,        comp(BesselComponent)],
  [CombinatoricsNode, comp(CombinatoricsComponent)],
  [TwoInputMathNode,  comp(TwoInputMathComponent)],
  [SumProductNode,    comp(SumProductComponent)],
  [ChooseNode,        comp(ChooseComponent)],
  [BooleanInputNode,  comp(BooleanInputComponent)],
  [SliderInputNode,   comp(SliderInputComponent)],
  [ColorPickerNode,   comp(ColorPickerComponent)],
  [ColorBlendNode,    comp(ColorBlendComponent)],
  [IsTestNode,      comp(IsTestComponent)],
  [NaNode,          comp(NaComponent)],
  [AlertNode,       comp(AlertComponent)],
  [NormalizeNode,   comp(NormalizeComponent)],
  [RepeatNode,      comp(RepeatComponent)],
  [ShuffleNode,     comp(ShuffleComponent)],
  [NthElementNode,  comp(NthElementComponent)],
  [InterleaveNode,  comp(InterleaveComponent)],
  [PadNode,         comp(PadComponent)],
  [GeometricNode,   comp(GeometricComponent)],
  [FibonacciNode,   comp(FibonacciComponent)],
  [StandardizeNode, comp(StandardizeComponent)],
  [CovarianceNode,  comp(CovarianceComponent)],
  [FisherNode,      comp(FisherComponent)],
  [BitwiseNode,     comp(BitwiseComponent)],
  [DepreciationNode, comp(DepreciationComponent)],
  // Must stay ABOVE EquationNode — the subclass fallback is an instanceof SCAN.
  [TvmNode,          comp(TvmComponent)],
  [IpmtPpmtNode,     comp(IpmtPpmtComponent)],
  [NpvNode,          comp(NpvComponent)],
  [IrrNode,          comp(IrrComponent)],
  [MirrNode,         comp(MirrComponent)],
  [CumPmtNode,       comp(CumPmtComponent)],
  [DistributionNode, comp(DistributionComponent)],
  [RegressionNode,   comp(RegressionComponent)],
  [ForecastNode,     comp(ForecastComponent)],
  [ModeNode,         comp(ModeComponent)],
  [TrimMeanNode,     comp(TrimMeanComponent)],
  [FrequencyNode,    comp(FrequencyComponent)],
  [ConfidenceNode,   comp(ConfidenceComponent)],
  [SeriesSumNode,    comp(SeriesSumComponent)],
  [MultinomialNode,  comp(MultinomialComponent)],
  [SwitchNode,       comp(SwitchComponent)],
  [IfsNode,          comp(IfsComponent)],
  [HypothesisTestNode, comp(HypothesisTestComponent)],
  [TrendNode,        comp(TrendComponent)],
  [InterpolateNode,  comp(InterpolateComponent)],
  [LinestNode,       comp(LinestComponent)],
  [LogestNode,       comp(LogestComponent)],
  [BinomDistRangeNode, comp(BinomDistRangeComponent)],
  [FvScheduleNode,   comp(FvScheduleComponent)],
  [IspmtNode,        comp(IspmtComponent)],
  [DollarNode,       comp(DollarComponent)],
  [ProbNode,         comp(ProbComponent)],
  [WeightedNode,     comp(WeightedComponent)],
  [BaseConvertNode,  comp(BaseConvertComponent)],
  [TextInputNode,  comp(TextInputComponent)],
  [TextTransformNode,comp(TextTransformComponent)],
  [TextLenNode,      comp(TextLenComponent)],
  [ConcatNode,       comp(ConcatComponent)],
  [TextSliceNode,    comp(TextSliceComponent)],
  [TextFindNode,     comp(TextFindComponent)],
  [SubstituteNode,   comp(SubstituteComponent)],
  [TextReplaceNode,  comp(TextReplaceComponent)],
  [ReptNode,              comp(ReptComponent)],
  [ExactNode,             comp(ExactComponent)],
  [CharCodeNode,          comp(CharCodeComponent)],
  [TextJoinNode,          comp(TextJoinComponent)],
  [TextSplitNode,         comp(TextSplitComponent)],
  [TextAfterBeforeNode,   comp(TextAfterBeforeComponent)],
  [NumberValueNode,       comp(NumberValueComponent)],
  [RomanArabicNode,       comp(RomanArabicComponent)],
  [FixedNode,             comp(FixedComponent)],
  [UrlEncodeNode,         comp(UrlEncodeComponent)],
  [TodayNowNode,          comp(TodayNowComponent)],
  [DateConstructNode,     comp(DateConstructComponent)],
  [TimeConstructNode,     comp(TimeConstructComponent)],
  [DateValueNode,         comp(DateValueComponent)],
  [TimeValueNode,         comp(TimeValueComponent)],
  [DatePartNode,          comp(DatePartComponent)],
  [WeekInfoNode,          comp(WeekInfoComponent)],
  [DateDiffNode,          comp(DateDiffComponent)],
  [DateAddNode,           comp(DateAddComponent)],
  [WorkdaysNode,          comp(WorkdaysComponent)],
  [RandArrayNode,         comp(RandArrayComponent)],
  [SortByNode,            comp(SortByComponent)],
  [XMatchNode,            comp(XMatchComponent)],
  [TBillNode,             comp(TBillComponent)],
  [SecurityDiscNode,      comp(SecurityDiscComponent)],
  [CouponNode,            comp(CouponComponent)],
  [AccrintNode,           comp(AccrintComponent)],
  [AccrintMNode,          comp(AccrintMComponent)],
  [PriceDiscNode,         comp(PriceDiscComponent)],
  [PriceMatNode,          comp(PriceMatComponent)],
  [DurationNode,          comp(DurationComponent)],
  [BondPriceNode,         comp(BondPriceComponent)],
  [OddCouponNode,         comp(OddCouponComponent)],
  [IsEvenOddNode,         comp(IsEvenOddComponent)],
  [FormatDollarNode,      comp(FormatDollarComponent)],
  [TableInputNode,        comp(TableInputComponent)],
  [MatDetNode,            comp(MatDetComponent)],
  [TableMultNode,         comp(TableMultComponent)],
  [TableUnitNode,         comp(TableUnitComponent)],
  [TableTransposeNode,    comp(TableTransposeComponent)],
  [HStackTableNode,       comp(HStackTableComponent)],
  [TableReshapeNode,      comp(TableReshapeComponent)],
  [TableSelectNode,       comp(TableSelectComponent)],
  [TableTakeDropNode,     comp(TableTakeDropComponent)],
  [ExpandNode,            comp(ExpandTableComponent)],
  [TableInfoNode,         comp(TableInfoComponent)],
  [MapTableNode,          comp(MapTableComponent)],
  [ByAxisNode,            comp(ByAxisComponent)],
  [MakeArrayNode,         comp(MakeArrayComponent)],
  [ReduceLambdaNode,      comp(ReduceLambdaComponent)],
  [ScanLambdaNode,        comp(ScanLambdaComponent)],
  [LambdaNode,            comp(LambdaComponent)],
  [FrameInputNode,        comp(FrameInputComponent)],
  [WebSourceNode,         comp(WebSourceComponent)],
  [DataFeedNode,          comp(DataFeedComponent)],
  [CsvConnectionNode,     comp(CsvConnectionComponent)],
  [ParquetConnectionNode, comp(ParquetConnectionComponent)],
  [ImportHtmlNode,        comp(ImportHtmlComponent)],
  [ImportXmlNode,         comp(ImportXmlComponent)],
  [WriteCsvNode,          comp(WriteCsvComponent)],
  [WriteJsonNode,         comp(WriteJsonComponent)],
  [WriteObsidianNode,     comp(WriteObsidianComponent)],
  [BuildFrameNode,        comp(BuildFrameComponent)],
  [SplitFrameNode,        comp(SplitFrameComponent)],
  [GetColumnNode,         comp(GetColumnComponent)],
  [AddColumnNode,         comp(AddColumnComponent)],
  [ComputedColumnNode,    comp(ComputedColumnComponent)],
  [GetRowNode,            comp(GetRowComponent)],
  [DistinctNode,          comp(DistinctComponent)],
  [HeadNode,              comp(HeadComponent)],
  [SortFrameNode,         comp(SortFrameComponent)],
  [FilterFrameNode,       comp(FilterFrameComponent)],
  [JoinNode,              comp(JoinComponent)],
  [SelectColumnsNode,     comp(SelectColumnsComponent)],
  [DropColumnsNode,       comp(DropColumnsComponent)],
  [GroupByFrameNode,      comp(GroupByFrameComponent)],
  [PivotNode,             comp(PivotComponent)],
  [UnpivotNode,           comp(UnpivotComponent)],
  [NestNode,              comp(NestComponent)],
  [UnnestNode,            comp(UnnestComponent)],
  [AppendNode,            comp(AppendComponent)],
  [RenameNode,            comp(RenameComponent)],
  [SplitColumnNode,       comp(SplitColumnComponent)],
  [AddIndexNode,          comp(AddIndexComponent)],
  [DecisionMatrixNode,    comp(DecisionMatrixComponent)],
  [DecisionSensitivityNode, comp(DecisionSensitivityComponent)],
  [ReconcileNode,         comp(ReconcileComponent)],
  [BuildCubeNode,         comp(BuildCubeComponent)],
  [NestJoinNode,          comp(NestJoinComponent)],
  [CubeColumnsNode,       comp(CubeColumnsComponent)],
  [CubeRollupNode,        comp(CubeRollupComponent)],
  [GroupNode,             comp(GroupComponent)],
  [CompositeNode,         comp(CompositeComponent)],
  // Boundary markers — rendered only inside the drill-in editor's own rete root.
  [CompositeInputNode,    comp(CompositeInputMarkerComponent)],
  [CompositeOutputNode,   comp(CompositeOutputMarkerComponent)],
  [ComplexFromNode,       comp(ComplexFromComponent)],
  [ComplexUnpackNode,     comp(ComplexUnpackComponent)],
  [ComplexUnaryNode,      comp(ComplexUnaryComponent)],
  [ComplexBinaryNode,     comp(ComplexBinaryComponent)],
  [ComplexPowerNode,      comp(ComplexPowerComponent)],
  [TextFilterNode,        comp(TextFilterComponent)],
  [FormatControllerNode,  comp(FormatControllerComponent)],
  [ExpressionNode,        comp(ExpressionComponent)],
  [EquationNode,          comp(EquationComponent)],
  [RegexNode,             comp(RegexComponent)],
  [GroupByNode,           comp(GroupByComponent)],
  // Packs: registered ALWAYS, so a saved graph renders with the pack deactivated.
  [HypotenuseNode,        comp(HypotenuseComponent)],
  [ParallelCombineNode,   comp(ParallelCombineComponent)],
  [ESeriesNode,           comp(ESeriesComponent)],
  [AwgNode,               comp(AwgComponent)],
  [PhysicsConstantNode,   comp(PhysicsConstantComponent)],
  [ColebrookNode,         comp(ColebrookComponent)],
  [IsaAtmosphereNode,     comp(IsaAtmosphereComponent)],
  [AntoineNode,           comp(AntoineComponent)],
  [IsInNode,              comp(IsInComponent)],
  [TallyNode,             comp(TallyComponent)],
  [ReverseTextNode,       comp(ReverseTextComponent)],
  [SpellNumberNode,       comp(SpellNumberComponent)],
  [SolarPositionNode,     comp(SolarPositionComponent)],
  [SunriseSunsetNode,     comp(SunriseSunsetComponent)],
  [MoonPhaseNode,         comp(MoonPhaseComponent)],
  [ElementNode,           comp(ElementComponent)],
  [ResistorCodeNode,      comp(ResistorCodeComponent)],
  [EmSpectrumNode,        comp(EmSpectrumComponent)],
  [HrZonesNode,           comp(HrZonesComponent)],
  [PipeRoughnessNode,     comp(PipeRoughnessComponent)],
  [TriangleSolverNode,    comp(TriangleSolverComponent)],
  [MolarMassNode,         comp(MolarMassComponent)],
  [PromoNode,             comp(PromoComponent)],
  // Load-time stand-in for an unregistered saved type (pack off / renamed).
  [PlaceholderNode,       comp(PlaceholderComponent)],
  [ExpectNode,            comp(ExpectComponent)],
  [TornadoNode,           comp(TornadoComponent)],
];

// Exact constructor first, then the ordered `instanceof` scan for subclasses that
// reuse a base component — so entry order matters only for UNregistered subclasses.
const componentByCtor = new Map<NodeCtor, AnyNodeComponent>(NODE_COMPONENTS);

export function componentForNode(payload: object): AnyNodeComponent | null {
  const exact = componentByCtor.get(payload.constructor as NodeCtor);
  if (exact) return exact;
  const hit = NODE_COMPONENTS.find(([Ctor]) => payload instanceof Ctor);
  return hit ? hit[1] : null;
}
