// Run with: npm run ai-grounding [-- --out <file>]
// Emits the model-facing grounding spec for authoring Solenoid graphs in the
// text form (backlog "AI command palette", D27): the grammar, the socket-type
// lattice, and the full node inventory — every class with its text-form `Type`
// token, sockets, inline-literal inputs, and op variants. GENERATED, never
// hand-edited: the classes and `nodeCatalog.ts` are the truth, this walks them
// (the same generate-don't-author move as the Add menu and the Function
// Reference). Prints to stdout; `--out` writes a file instead.

import { writeFileSync } from "node:fs";
import { ClassicPreset } from "rete";
import { buildCatalog } from "../src/graph/catalogUtils";
import type { CatalogEntry, NodeCatalogEntry, CatalogCategory } from "../src/graph/AddNodeMenu";
import { SolenoidSocket, SOCKET_TYPE_LABELS, elementFamilyOf, latticeRank, type SocketDataType } from "../src/graph/sockets";
import { INIT_FIELD_ORDER, INIT_EXTRA_FIELD_ORDER } from "../src/graph/copyPaste";

// ─── Socket signature of a headless instance ────────────────────────────────────

function sig(record: Record<string, unknown> | undefined): string {
  const parts: string[] = [];
  for (const [k, port] of Object.entries(record ?? {})) {
    if (!port || typeof port !== "object") continue;
    const p = port as { socket?: unknown; multipleConnections?: unknown };
    const t = p.socket instanceof SolenoidSocket ? p.socket.dataType : "?";
    parts.push(`${k}:${t}${p.multipleConnections === true ? "*" : ""}`);
  }
  return parts.join(", ");
}

interface ClassInfo {
  ctorName: string;
  path: string[];
  variants: Array<{ leaf: NodeCatalogEntry; op: string | null; inputs: string; outputs: string }>;
  litKeys: string[];
  strKeys: string[];
  hidden: boolean;
}

// ─── Walk the full catalog (packs included), grouping leaves by class ───────────

const classes = new Map<string, ClassInfo>();
const order: string[] = [];

function visit(entries: CatalogEntry[], path: string[]): void {
  for (const e of entries) {
    if (e.type === "category") {
      visit((e as CatalogCategory).children, [...path, (e as CatalogCategory).label]);
    } else if (e.type === "pair") {
      visit((e as { children: CatalogEntry[] }).children, path);
    } else {
      const leaf = e as NodeCatalogEntry;
      let inst: ClassicPreset.Node;
      try {
        inst = leaf.create() as ClassicPreset.Node;
      } catch {
        continue; // a factory that can't construct standalone has no authoring story
      }
      const anyInst = inst as unknown as Record<string, unknown>;
      const ctorName = inst.constructor.name;
      let info = classes.get(ctorName);
      if (!info) {
        info = {
          ctorName,
          path,
          variants: [],
          litKeys: typeof anyInst.literals === "object" && anyInst.literals ? Object.keys(anyInst.literals as object) : [],
          strKeys: typeof anyInst.stringLiterals === "object" && anyInst.stringLiterals ? Object.keys(anyInst.stringLiterals as object) : [],
          hidden: leaf.hidden === true,
        };
        classes.set(ctorName, info);
        order.push(ctorName);
      }
      info.hidden = info.hidden && leaf.hidden === true; // hidden only if EVERY leaf is
      info.variants.push({
        leaf,
        op: typeof anyInst.op === "string" ? (anyInst.op as string) : null,
        inputs: sig(anyInst.inputs as Record<string, unknown> | undefined),
        outputs: sig(anyInst.outputs as Record<string, unknown> | undefined),
      });
    }
  }
}

visit(buildCatalog(false), []);

// ─── Emit ───────────────────────────────────────────────────────────────────────

const out: string[] = [];
const w = (s = "") => out.push(s);

w(`# Solenoid graph authoring — grounding spec`);
w();
w(`GENERATED by \`npm run ai-grounding\` from \`nodeCatalog.ts\` and the live node`);
w(`classes — regenerate rather than edit. This is the vocabulary for reading and`);
w(`writing a Solenoid document's text form.`);
w();
w(`## The text form`);
w();
w(`One node per line, dependency (topological) order, then a \`---\` line, then one`);
w(`JSON "sidecar" block carrying everything that isn't logic (positions, standoffs,`);
w(`pins, comments, the save version \`v\`). Node line grammar:`);
w();
w("```");
w(`Name: Type key=<JSON value> lit:key=<JSON number> str:key=<JSON string> input<-Other.output`);
w("```");
w();
w(`- \`Name\` — unique per document, \`[A-Za-z_][A-Za-z0-9_]*\`. Connections address it.`);
w(`- \`Type\` — a node CLASS name from the inventory below (e.g. \`FilterNode\`).`);
w(`- \`key=…\` — an init field (construction config, e.g. \`op="npv"\`). Values are JSON-encoded.`);
w(`- \`lit:key=…\` / \`str:key=…\` — an inline value typed into an input row instead of wiring it;`);
w(`  only classes listing "inline:" below accept them, on the keys listed.`);
w(`- \`input<-Source.output\` — an incoming cable, named by the source node and its output key.`);
w(`- Positions are optional (the sidecar's \`positions\` map; omitted nodes land at 0,0 —`);
w(`  the app's Tidy can lay a generated graph out).`);
w();
w(`Example:`);
w();
w("```");
w(`Price: NumberInputNode label="Price" value=25`);
w(`Qty: NumberInputNode label="Qty" value=4`);
w(`Total: ArithmeticNode op="mul" a<-Price.value b<-Qty.value`);
w(`Show: DisplayNode in<-Total.result`);
w(`---`);
w(`{ "v": 2, "positions": { "Price": { "x": 0, "y": 0 } } }`);
w("```");
w();
w(`Validate before applying or running: \`npm run validate-graph <file>\`;`);
w(`run headlessly: \`npm run run-graph <file>\`.`);
w();
w(`## Socket types`);
w();
w(`Cables are typed. An output can feed an input when the lattice allows it:`);
w(`values flow UP in dimensionality (scalar → list → matrix; a list enters a 2-D`);
w(`input as one ROW) and never narrow back down (reshape explicitly instead);`);
w(`element families (number / text / date / complex / boolean) never auto-cross —`);
w(`a Cast node converts, and the sole built-in bridge is boolean↔number. \`frame\``);
w(`(named typed columns) and \`cube\` are their own families with their own verbs.`);
w(`Wildcards: \`any\` = untyped scalar, \`anylist\`/\`anytable\` = untyped 1-D/2-D,`);
w(`\`trueany\` adopts anything. A \`*\` after an input below marks a multi-cable input.`);
w();
w(`| type | meaning | family | rank |`);
w(`|---|---|---|---|`);
for (const [t, label] of Object.entries(SOCKET_TYPE_LABELS)) {
  const fam = elementFamilyOf(t as SocketDataType) ?? "—";
  const rank = latticeRank(t as SocketDataType);
  w(`| \`${t}\` | ${label} | ${fam} | ${rank ?? "—"} |`);
}
w();
w(`## Init-field whitelist`);
w();
w(`Only these keys ever persist as \`key=\` init fields (which apply to which class`);
w(`follows from the class's own config — \`op\` selects a variant, \`label\` titles the`);
w(`card, etc.):`);
w();
w("```");
w([...INIT_FIELD_ORDER, ...INIT_EXTRA_FIELD_ORDER].join(" "));
w("```");
w();
w(`## Node classes`);
w();
w(`\`Type\` tokens for the text form. "inline:" lists the input keys that accept`);
w(`\`lit:\`/\`str:\` values. Where one class hosts several ops, each variant line is`);
w(`\`op="…" — label\`; sockets are shown per variant only when they differ.`);

let lastTop = "";
for (const ctorName of order) {
  const info = classes.get(ctorName)!;
  if (info.hidden) continue; // deprecated: loads, but must not be authored
  const top = info.path[0] ?? "Other";
  if (top !== lastTop) {
    w();
    w(`### ${top}`);
    lastTop = top;
  }
  const first = info.variants[0];
  const allSameSockets = info.variants.every((v) => v.inputs === first.inputs && v.outputs === first.outputs);
  const ops = info.variants.filter((v) => v.op !== null);
  w();
  w(`#### \`${ctorName}\`${info.variants.length === 1 ? ` — ${first.leaf.label}` : ""}`);
  if (first.leaf.description) w(first.leaf.description);
  if (allSameSockets) {
    w(`- in: ${first.inputs || "—"}`);
    w(`- out: ${first.outputs || "—"}`);
  }
  const inline: string[] = [];
  if (info.litKeys.length > 0) inline.push(`lit: ${info.litKeys.join(", ")}`);
  if (info.strKeys.length > 0) inline.push(`str: ${info.strKeys.join(", ")}`);
  if (inline.length > 0) w(`- inline: ${inline.join(" · ")}`);
  if (info.variants.length > 1) {
    for (const v of info.variants) {
      const opPart = v.op !== null ? `op=${JSON.stringify(v.op)} — ` : "";
      const sockets = allSameSockets ? "" : ` (in: ${v.inputs || "—"} → out: ${v.outputs || "—"})`;
      w(`- ${opPart}${v.leaf.label}${sockets}`);
    }
  }
}
w();

const text = out.join("\n");
const outIdx = process.argv.indexOf("--out");
if (outIdx !== -1 && process.argv[outIdx + 1]) {
  writeFileSync(process.argv[outIdx + 1], text);
  console.error(`wrote ${process.argv[outIdx + 1]} (${text.length} chars, ${classes.size} classes)`);
} else {
  console.log(text);
}
